// Code generated by cmd/consoletypes. DO NOT EDIT.
//
// The console's data contract, generated from the Go view structs (docs/adr/ADR-007-console-type-generation.md).
//
// This file is CHECKED IN and regenerated in CI; a difference fails the build. That gate is the whole
// point: the failure mode of a hand-maintained type is not a compile error, it is a blank cell in
// production, because a field renamed in Go becomes `undefined` in TypeScript and renders as an
// em-dash that looks exactly like legitimately absent data.
//
// Two shapes to note, because they are contract facts rather than generator quirks:
//
//   `T[] | null`   a nil Go slice marshals as null, not []. The contract says so rather than
//                  pretending otherwise; a consumer that assumes an array fails exactly once, in
//                  production.
//   `T | null`     a pointer field is nullable. Null and ABSENT are different facts, and
//                  conflating them makes a UI render "absent" for a value the server called null.
//
// To change anything here: change the Go view struct, then run `make console-types`.

/** The closed set of things the conversational console may say (P31 FR1). A kind added in Go and missing here fails the console type-check rather than rendering blank. */
export type ConversationKind =
    "plan"
  | "progress"
  | "finding"
  | "proposal"
  | "approval_request"
  | "result"
  | "refusal"
  | "answer"
;

/** Whether a message replayed a pinned inference or was generated in this turn. Without it P30's determinism guarantee is unfalsifiable, and therefore a claim rather than a guarantee. */
export type ConversationProvenance = "pinned" | "generated";

/** The five phases a turn advances through. A turn that cannot name its phase is a defect, not a slow turn. */
export type ConversationPhase = "understand" | "plan" | "act" | "verify" | "respond";

/** How one planned step resolved. Everything except `done` names a reason — a `skipped` with no reason is the omission problem with a label on it. */
export type ConversationStepState = "done" | "skipped" | "refused" | "not_measured";

/** The four states of a finding. They render differently or the component is wrong. */
export type ConversationFindingState = "measured" | "not_measured" | "refused" | "stale";

/** 503 not-mounted, 404 not-found, transport. Three things a person does three different things about; one apologetic sentence tells them to do none. */
export type ConversationFailureClass = "not_mounted" | "not_found" | "transport";

/** Why a run ended, from the harness runtime's own closed set — the SAME vocabulary a node loop uses. Expand-only: it participates in `version_id`. */
export type StopReason =
    "satisfied"
  | "ceiling"
  | "single-shot"
  | "token-budget"
  | "tool-call-ceiling"
  | "wall-clock"
  | "cancelled"
  | "spend-ceiling"
;

/** The fourteen things this surface can be asked. Equal, by fence, to the set of working surfaces. */
export type ConversationIntent =
    "graph"
  | "run_history"
  | "compare"
  | "preview_change"
  | "deliver"
  | "prompt_model"
  | "author"
  | "graph_order"
  | "context"
  | "memory"
  | "harness"
  | "coverage"
  | "assess"
  | "improve"
;

/** The four reasons a clone failed. A rotated token and a renamed default branch are different people's problems on different days; one message sends both to the same wrong place. */
export type CloneCause = "credential_rejected" | "network" | "repository_not_found" | "revision_not_found";

/** The three code hosts a repository can be connected from. Each expresses its narrowest grant differently (PRD §14 A2). */
export type SourceForge = "bitbucket" | "github" | "gitlab";

/** What one entry in the read ledger records: a success, or one of the four causes. FIVE members, because an outcome the browser does not recognise renders as nothing, which in a list of reads is indistinguishable from a read that succeeded. */
export type CloneOutcome =
    "credential_rejected"
  | "network"
  | "repository_not_found"
  | "revision_not_found"
  | "succeeded"
;

/** Whether a person was present for a read. The distinction the whole disclosure exists for: a connection is usable when the customer is not there. */
export type SourceActor = "person" | "scheduled";

/** How the forge issued the read grant. Per forge, per PRD §14 A2 — an App where one exists, a repository-scoped token where it does not. */
export type SourceGrantKind = "app_installation" | "access_token";

/** Where a local-mode pairing is. `expired` is a distinct state rather than a deletion, because "your code expired" and "no such code" send a person to two different places. */
export type PairingState = "expired" | "paired" | "pending";

/** The nine surfaces an assessment reports on, in report order. The seven that are also configuration dimensions are READ from variantspec, so the console, the CLI and the report cannot name a surface differently. */
export type AssessmentAxis =
    "model"
  | "prompt"
  | "skills"
  | "context"
  | "tools"
  | "memory"
  | "harness"
  | "loop"
  | "graph"
;

/** How a finding's claim was established. Four, in evidence-strength order. `not_measured` is a different message from `observed`, not a dimmer one — a component that renders three states, or renders the fourth greyed out, is wrong. */
export type AssessmentState = "measured" | "observed" | "not_measured" | "refused";

/** What produced a finding. `inferred` must be visible without hovering: a reader scanning the report has to be able to see how much of it a model wrote. */
export type AssessmentOrigin = "structural" | "inferred";

/** The closed set of things a `not_measured` finding can name. Closed rather than free text because health is grouped by it and because four of these must render four distinct messages — a console cannot hold distinct messages against an open set. */
export type AssessmentMissingInput =
    "no_runnable_entry_point"
  | "missing_credential"
  | "sandbox_refusal"
  | "unsupported_language"
  | "frontend_emits_no_edges"
  | "unresolved_in_ir"
  | "no_source_snapshot"
  | "no_call_sites_discovered"
  | "not_visible_in_static_ir"
  | "budget_exhausted"
  | "inference_abstained"
;

/** Which of exactly three things this build lacks. Never a generic "unsupported": the three send a reader to three different places and only one is the customer's problem. */
export type AssessmentRefusalCause = "frontend" | "analysis" | "language";

/** Which input moved when a re-inference changed a finding: the source, our configuration, or the provider's model. Only the first is a fact about the customer — and `unattributable` is not a leftover bucket, it is FR15's determinism guarantee failing. */
export type AssessmentDiffCause = "source" | "agent_config" | "provider_model" | "unattributable";

/** The three existing read models a finding's evidence points into. The assessment is an index over evidence the platform already holds, never a second place a number is computed. */
export type AssessmentEvidenceSurface = "graph" | "board" | "scorecard";

/** How a workflow's source arrives: a pushed bundle (the default), a connected repository, or a local path. No feature is gated on any of them. */
export type SourceMode = "bundle" | "connected" | "local";

/** Response of `GET /api/v1/runs/{run_id}`. */
export interface RunView {
  run_id: string;
  config_hash: string;
  config_hash_display: string;
  source_revision: string;
  seed: number;
  status: string;
  halted_node_id?: string;
  halted_reason?: string;
  nodes: NodeView[] | null;
}

export interface NodeView {
  node_id: string;
  attempt_group: number;
  status: string;
  input_blob_hash?: string;
  output_blob_hash?: string;
  idempotency_key: string;
  error?: string;
}

/** Response of `GET /api/v1/transforms/{config_hash}/{source_revision}`. */
export interface TransformView {
  config_hash: string;
  config_hash_display: string;
  source_revision: string;
  status: string;
  verification_strength: string;
  requires_human_review: boolean;
  variant_branch?: string;
  variant_commit?: string;
  diff: string;
  diff_hash?: string;
  build_log?: string;
  rejected_node_id?: string;
  rejected_dimension?: string;
}

/** Response of `GET /api/v1/transforms/{config_hash}/{source_revision} (origin: reported)`. */
export interface ReportedTransformView {
  origin: string;
  config_hash: string;
  config_hash_display: string;
  source_revision: string;
  source_revision_display: string;
  workflow_id: string;
  status: string;
  tool_version: string;
  coverage_version?: string;
  reported_at: string;
  node_outcomes: WireNodeOutcome[] | null;
  nodes_applied: number;
  nodes_refused: number;
  files_changed: number;
  lines_added: number;
  lines_removed: number;
  diff_available: boolean;
  diff_absent_because: string;
}

export interface WireNodeOutcome {
  node_id: string;
  outcome: string;
  cause?: string;
}

/** Response of `POST /api/v1/specs/submit`. */
export interface SubmitResult {
  config_hash: string;
  config_hash_display: string;
  source_revision: string;
  transform_status: string;
  variant_branch?: string;
  variant_commit?: string;
  diff_hash?: string;
  run_id?: string;
  rejected_node_id?: string;
  rejected_dimension?: string;
}

/** Response of `POST /api/v1/specs/{resolve,submit} (rejection)`. */
export interface SpecError {
  error: string;
  node_id?: string;
  dimension?: string;
  ref?: string;
}

/** Response of `GET /api/v1/runs/{run_id}/monitor`. */
export interface RunMonitor {
  run_id: string;
  config_hash: string;
  status: string;
  terminal: boolean;
  nodes: RunMonitorNode[] | null;
  halted?: RunMonitorHalted | null;
}

export interface RunMonitorNode {
  node_id: string;
  state: string;
  latency_ms: number;
  cost_usd: number;
  tokens_prompt: number;
  tokens_completion: number;
}

export interface RunMonitorHalted {
  node_id: string;
  reason: string;
}

/** Response of `GET /api/v1/workflows/{workflow_id}/pattern-graph`. */
export interface GraphView {
  workflow_id: string;
  ir_version: string;
  taxonomy_version: string;
  nodes: ViewNode[] | null;
  edges: ViewEdge[] | null;
  regions: ViewRegion[] | null;
  unclassified: ViewRegion[] | null;
  diagnostics?: Diagnostic[] | null;
  llm_calls: number;
  llm_calls_note: string;
  topology?: ViewTopology | null;
  composition: Composition;
  agent?: ViewAgent | null;
}

export interface ViewNode {
  node_id: string;
  symbol: string;
  model: string;
  policy: string;
  tools: number;
  layer: number;
  order: number;
  labels: ViewLabel[] | null;
  region_ids: string[] | null;
}

export interface ViewLabel {
  pattern: string;
  ordinal: number;
  title: string;
  group: string;
  confidence: number;
  source: string;
  candidate: boolean;
  provenance: string;
  primary_metric: string;
  metrics: string[] | null;
  author?: string;
}

export interface ViewEdge {
  from: string;
  to: string;
  kind: string;
  author?: string;
  confidence?: number;
}

export interface ViewRegion {
  subgraph_id: string;
  node_ids: string[] | null;
  labels: ViewLabel[] | null;
  reason?: string;
  reason_sentence?: string;
}

export interface Diagnostic {
  stage: string;
  subgraph_ref?: string;
  raw_pattern?: string;
  source?: string;
  reason: string;
}

export interface ViewTopology {
  reason: string;
  frontends: ViewFrontend[] | null;
  sentence: string;
}

export interface ViewFrontend {
  language: string;
  analysis_kind: string;
  nodes: number;
  edges: number;
}

export interface Composition {
  patterns: CompositionPattern[] | null;
  nodes_total: number;
  nodes_covered: number;
  nodes_covered_inferred: number;
  unlabelled_remainder: number;
  edges_total: number;
  edges_inferred: number;
}

export interface CompositionPattern {
  pattern: string;
  ordinal: number;
  title: string;
  group: string;
  regions: number;
  nodes: number;
  provenance: string[] | null;
  authors: string[] | null;
  state: string;
  candidate: boolean;
}

export interface ViewAgent {
  state: string;
  state_sentence: string;
  placement: string;
  placement_sentence?: string;
  narrative?: string;
  action: string;
  action_reason?: string;
  failure?: string;
}

/** Response of `GET /api/v1/workflows/{workflow_id}/eval-board`. */
export interface BoardView {
  state: string;
  error?: string;
  workflow_id: string;
  eval_set_hash: string;
  profile: string;
  gate_set: string;
  profiles: string[] | null;
  progress: Progress;
  ranked: Row[] | null;
  disqualified: Row[] | null;
  pareto: ParetoPoint[] | null;
  coverage: CoverageView;
  spend: SpendReport;
  all_tie: boolean;
  tie_analysis: string;
  cost_latency: string;
  notes?: string[] | null;
  unmeasured?: UnmeasuredView[] | null;
  runs_enqueued: number;
}

export interface Progress {
  units_planned: number;
  units_completed: number;
  seed_floor: number;
}

export interface Row {
  rank: number;
  variant_id: string;
  label: string;
  config_hash: string;
  config_hash_short: string;
  score: number;
  ci_low: number;
  ci_high: number;
  n_seeds: number;
  n_cases: number;
  method: string;
  components: ComponentView[] | null;
  penalties?: PenaltyView[] | null;
  gate_pass: boolean;
  failed_gates?: string[] | null;
  gate_reasons?: string[] | null;
  flags?: string[] | null;
  tied_with?: string[] | null;
  provisional: boolean;
}

export interface ComponentView {
  metric: string;
  role: string;
  raw: number;
  raw_ci_low: number;
  raw_ci_high: number;
  normalized: number;
  contribution: number;
  unit: string;
  judge?: JudgeStanding | null;
}

export interface JudgeStanding {
  metric: string;
  agreement: number;
  percent_agreement: number;
  n_human: number;
  floor: number;
  calibrated: boolean;
}

export interface PenaltyView {
  term: string;
  amount: number;
}

export interface ParetoPoint {
  variant_id: string;
  label: string;
  quality: number;
  cost_usd: number;
  latency_ms: number;
  non_dominated: boolean;
  composite: number;
}

export interface CoverageView {
  measured: boolean;
  dimensions: DimensionView[] | null;
  residual: ResidualItem[] | null;
  met: boolean;
  iterations: number;
  stopped_because?: string;
  n_cases: number;
  difficulty: number;
  difficulty_measured: boolean;
  diversity: number;
  oracle_coverage: number;
  n_oracle: number;
  n_indecisive: number;
  n_gold: number;
  n_weak: number;
  n_none: number;
  low_confidence: boolean;
  reasons?: string[] | null;
}

export interface DimensionView {
  name: string;
  achieved: number;
  target: number;
  covered: number;
  total: number;
  met: boolean;
  uncovered?: string[] | null;
  vacuous?: boolean;
}

export interface ResidualItem {
  id: string;
  dimension: string;
  kind: string;
  unreachable: boolean;
  reason: string;
}

export interface SpendReport {
  eval_run_id: string;
  by_kind: Record<string, number>;
  calls_by_kind: Record<string, number>;
  total_usd: number;
  budget: Budget;
  exhausted?: string[] | null;
}

export interface Budget {
  total_usd?: number | null;
  judge_usd?: number | null;
  generation_usd?: number | null;
  max_judge_calls?: number;
  max_generation_calls?: number;
}

export interface UnmeasuredView {
  variant_id: string;
  label: string;
  reason: string;
}

/** Response of `GET /api/v1/workflows/{workflow_id}/eval-set`. */
export interface EvalSetView {
  workflow_id: string;
  state: string;
  sentence: string;
  n_cases: number;
  cases: EvalCaseView[] | null;
  families: FamilyCount[] | null;
  n_oracle: number;
  n_indecisive: number;
  indecisive_reasons: string[] | null;
  vacuous_dimensions: string[] | null;
  uncovered_nodes: string[] | null;
  unattributed: string[] | null;
}

export interface EvalCaseView {
  case_id: string;
  family: string;
  oracle: string;
  indecisive: boolean;
}

export interface FamilyCount {
  family: string;
  cases: number;
}

/** Response of `GET /api/v1/variants/{variant_id}/scorecard`. */
export interface ScorecardView {
  variant_id: string;
  eval_set_hash: string;
  config_hash: string;
  workflow_id: string;
  state: string;
  message?: string;
  overall: OverallMetrics;
  nodes: NodeRow[] | null;
  clusters: ClusterRow[] | null;
  diagnoses: DiagnosisCard[] | null;
  ablations: AblationCard[] | null;
  analyst: AnalystStatus;
  topology: TopologyView;
  partial: boolean;
  has_inconclusive: boolean;
  analyst_uncalibrated: boolean;
  classified_node_count: number;
  unclassified_node_count: number;
  failure_attribution: string;
  read_only: boolean;
}

export interface OverallMetrics {
  task_success: number;
  n_cases: number;
  n_failing: number;
  cost_usd: number;
  latency_ms: number;
}

export interface NodeRow {
  node_id: string;
  failure_share: number;
  first_divergence_count: number;
  mean_cost_share: number;
  mean_latency_share: number;
  bottleneck_dimensions?: string[] | null;
  pattern?: string;
  classified: boolean;
}

export interface ClusterRow {
  signature: string;
  label: string;
  size: number;
  representative_case_id: string;
  member_case_ids: string[] | null;
}

export interface DiagnosisCard {
  code: string;
  description: string;
  node_id: string;
  source: string;
  confidence: number;
  evidence_case_ids: string[] | null;
  agreement: number;
  n_human: number;
  calibrated: boolean;
  analyst_flagged: boolean;
  low_confidence: boolean;
  classified: boolean;
}

export interface AblationCard {
  node_id: string;
  metric: string;
  delta_mean: number;
  ci_low: number;
  ci_high: number;
  n_seeds: number;
  verdict: string;
}

export interface AnalystStatus {
  present: boolean;
  agreement: number;
  n_human: number;
  calibrated: boolean;
  floor: number;
  flagged: boolean;
}

export interface TopologyView {
  edges: EdgeView[] | null;
  ordered_by_topology: boolean;
  provenance?: string;
}

export interface EdgeView {
  from: string;
  to: string;
  provenance: string;
  signal: string;
  confidence: number;
}

/** Response of `GET /api/v1/workflows/{workflow_id}/proposals`. */
export interface ProposalSurface {
  workflow_id: string;
  automation_level: string;
  state: string;
  error?: string;
  pass?: PassView | null;
  recommendations: Card[] | null;
  withheld: Card[] | null;
  trend: TrendView;
}

export interface PassView {
  state: string;
  detail: string;
  proposals: number;
  ran_at_ms: number;
}

export interface Card {
  proposal_id: string;
  operator: string;
  node_id: string;
  pattern: string;
  diag_id: string;
  evidence_case_ids: string[] | null;
  rationale: string;
  source_diff: string;
  spec_diff: DimChange[] | null;
  build_status: string;
  state: string;
  gate_result: string;
  held_out: boolean;
  held_out_label: string;
  delta: number;
  ci_low: number;
  ci_high: number;
  significant: boolean;
  cost_delta: number;
  latency_delta: number;
  cases_fixed: string[] | null;
  cases_broken: string[] | null;
  narration: string;
  can_open_pr: boolean;
  pr_disabled_reason?: string;
  refused_node_id?: string;
  refused_dimension?: string;
  refused_reason?: string;
}

export interface DimChange {
  node_id: string;
  dimension: string;
  from: string;
  to: string;
  kind?: string;
  items?: string[] | null;
}

export interface TrendView {
  points: TrendPoint[] | null;
  globally_improved: boolean;
  problems_moved: boolean;
  narrative: string;
}

export interface TrendPoint {
  variant_id: string;
  iteration: number;
  overall_success: number;
  cluster_sizes: Record<string, number>;
}

/** Response of `POST /api/v1/workflows/{workflow_id}/proposals/{proposal_id}/open-pr`. */
export interface PRResult {
  proposal_id: string;
  branch: string;
  url: string;
  draft: boolean;
  rollback: string;
}

/** Response of `GET /api/v1/customers/{customer_id}/billing`. */
export interface BillingView {
  customer_id: string;
  period: string;
  available_periods?: string[] | null;
  sum: number;
  sum_unit: string;
  sum_trend?: PeriodPoint[] | null;
  link_coverage?: LinkCoverageView | null;
  meters: MeterView[] | null;
  plan_id: string;
  plan_name: string;
  plan_config_version: string;
  entitlements: EntitlementRow[] | null;
  invoice: InvoiceView;
  state: BillingStateView;
  savings: SavingsView;
  denial?: DenialView | null;
  drift?: DriftView[] | null;
  empty: boolean;
}

export interface PeriodPoint {
  period: string;
  sum: number;
  baseline_sum: number;
  optimized_sum: number;
}

export interface LinkCoverageView {
  runs_linked: number;
  runs_reported: number;
  known: boolean;
  complete: boolean;
}

export interface MeterView {
  metric: string;
  label: string;
  value: number;
  unit: string;
  allowed: number;
  unlimited: boolean;
  over: boolean;
  reported_to_provider: boolean;
  provider_usage_ref?: string;
}

export interface EntitlementRow {
  feature: string;
  label: string;
  included: boolean;
  reason?: string;
  upgrade_plan?: string;
  upgrade_plan_name?: string;
}

export interface InvoiceView {
  invoice_ref?: string;
  status?: string;
  lines: LineView[] | null;
  totals?: TotalView[] | null;
}

export interface LineView {
  kind: string;
  label: string;
  basis: string;
  amount_ref?: string;
  quantity: number;
  unit?: string;
  charge_ref?: string;
  evidence?: EvidenceView[] | null;
  corrects?: string;
}

export interface EvidenceView {
  kind: string;
  ref: string;
  label: string;
  link?: string;
  method?: MethodView | null;
}

export interface MethodView {
  id: string;
  eval_set_hash: string;
  holdout_cases: number;
  generating_cases: number;
  seeds: number;
  baseline_config_hash: string;
  candidate_config_hash: string;
  significance_note?: string;
}

export interface TotalView {
  kind: string;
  label: string;
  lines: number;
  quantity: number;
}

export interface BillingStateView {
  invoice_status?: string;
  subscription_status?: string;
  payment_failed: boolean;
  past_due: boolean;
  guidance?: string;
}

export interface SavingsView {
  gainshare_consent: boolean;
  consented_at?: string;
  consent_available: boolean;
  baseline_sum: number;
  optimized_sum: number;
  verified_savings: number;
  unit: string;
  billed?: SavingRow[] | null;
  excluded?: ExcludedRow[] | null;
  none_verified: boolean;
}

export interface SavingRow {
  ref: string;
  baseline_sum: number;
  optimized_sum: number;
  savings: number;
  merge_commit: string;
  method?: MethodView | null;
}

export interface ExcludedRow {
  ref: string;
  reason: string;
  would_have_been: number;
}

export interface DenialView {
  feature: string;
  feature_label: string;
  reason: string;
  reason_code: string;
  upgrade_plan?: string;
  upgrade_plan_name?: string;
  limit?: DenialLimitView | null;
}

export interface DenialLimitView {
  limit: string;
  label: string;
  allowed: number;
  observed: number;
  period: string;
}

export interface DriftView {
  kind: string;
  metric: string;
  detail: string;
  platform_quantity: number;
  provider_quantity: number;
}

/** Response of `GET /api/v1/customers/{customer_id}/payment`. */
export interface PaymentView {
  billing: BillingView;
  plans: PlanOptionView[] | null;
  payment_method: PaymentMethodView;
  collection_available: boolean;
  pricing_issue?: PricingIssueView | null;
  unavailable?: BillingUnavailableView | null;
}

export interface PlanOptionView {
  plan_id: string;
  name: string;
  rank: number;
  current: boolean;
  direction: string;
  subscribable: boolean;
  unavailable: boolean;
}

export interface PaymentMethodView {
  present: boolean;
  brand?: string;
  last4?: string;
  status?: string;
  reason?: string;
  restore_path?: string;
}

export interface PricingIssueView {
  plans: string[] | null;
  checked_at?: string;
}

export interface BillingUnavailableView {
  detail: string;
  retryable: boolean;
}

/** Response of `POST /api/v1/customers/{customer_id}/checkout-session`. */
export interface CheckoutView {
  url?: string;
  client_secret?: string;
  session_ref?: string;
  expires_at?: string;
}

/** Response of `POST /api/v1/customers/{customer_id}/plan`. */
export interface PlanChangeView {
  plan_id: string;
  plan_name: string;
  status?: string;
  changed: boolean;
  checkout_required: boolean;
}

/** Response of `GET /api/v1/runs/{run_id}/link`. */
export interface LinkedRunView {
  run_id: string;
  workflow_id: string;
  config_hash: string;
  config_hash_display: string;
  source_revision: string;
  tool_version: string;
  linked_at: string;
  scores: LinkedScoreView[] | null;
}

export interface LinkedScoreView {
  metric: string;
  value: number;
  ci_low: number;
  ci_high: number;
}

/** Response of `GET /api/v1/deliveries`. */
export interface DeliveriesView {
  deliveries: DeliveryView[] | null;
  route: RouteConditionView;
}

export interface DeliveryView {
  delivery_id: string;
  state: string;
  config_hash: string;
  source_revision: string;
  target: string;
  mode: string;
  forge_ref: string;
  reason?: string;
  merge_commit?: string;
  proposal_ref: string;
}

export interface RouteConditionView {
  kind: string;
  detail?: string;
  next_action?: string;
  targets?: string[] | null;
}

/** Response of `GET /api/v1/coverage`. */
export interface AxisCoverageView {
  version: string;
  languages: string[] | null;
  axes: string[] | null;
  causes: CoverageCause[] | null;
  cells: CoverageCell[] | null;
}

export interface CoverageCause {
  id: string;
  owner: string;
  label: string;
}

export interface CoverageCell {
  axis: string;
  language: string;
  form: string;
  status: string;
  cause?: string;
  missing_artifact?: string;
  note?: string;
}

/** Response of `GET /api/v1/change-delivery`. */
export interface ChangeDeliveryView {
  version: string;
  routes: DeliveryRouteMeta[] | null;
  causes: DeliveryCauseMeta[] | null;
  states: DeliveryStateMeta[] | null;
  languages: string[] | null;
  cells: DeliveryCellView[] | null;
  source_cells: DeliverySourceCellView[] | null;
}

export interface DeliveryRouteMeta {
  id: string;
  label: string;
  permanence: string;
}

export interface DeliveryCauseMeta {
  id: string;
  owner: string;
  permanent: boolean;
  label: string;
}

export interface DeliveryStateMeta {
  id: string;
  label: string;
}

export interface DeliveryCellView {
  axis: string;
  change: string;
  route: string;
  status: string;
  cause?: string;
  owner?: string;
  permanent?: boolean;
  missing_artifact?: string;
  note?: string;
  contingent?: boolean;
  missing_component?: string;
  bound_only?: boolean;
}

export interface DeliverySourceCellView {
  change: string;
  language: string;
  status: string;
  cause?: string;
  permanent?: boolean;
  missing_artifact?: string;
  note?: string;
}

/** Response of `GET /api/v1/install`. */
export interface InstallView {
  matrix_version: string;
  documented_release: string;
  ratified_posture: string;
  delivered?: DeliveredTrustView | null;
  targets: TargetView[] | null;
  channels: ChannelView[] | null;
}

export interface DeliveredTrustView {
  version: string;
  signing_key_id?: string;
  claims: ClaimView[] | null;
}

export interface ClaimView {
  id: string;
  text: string;
  earned: boolean;
}

export interface TargetView {
  key: string;
  platform: string;
  arch: string;
  support: string;
  runner?: string;
  limit?: string;
  answer?: string;
  channels: string[] | null;
}

export interface ChannelView {
  id: string;
  label: string;
  oses: string[] | null;
  delivered: boolean;
  publication: string;
  blocker?: string;
  verification: string;
  manager_owned: boolean;
  install: string;
  upgrade: string;
  uninstall: string;
  pin: string;
}

/** Response of `GET /api/v1/repo-connections`. */
export interface ConnectionsView {
  connections: ConnectionView[] | null;
  forges: ForgeDescription[] | null;
  local_mode_deployments: string[] | null;
  retention_hours: number;
}

export interface ConnectionView {
  connection_id: string;
  workflow_id: string;
  mode: SourceMode;
  forge: SourceForge;
  repository: string;
  sub_path?: string;
  grant_kind: SourceGrantKind;
  grant_label: string;
  revoke_hint: string;
  created_by: string;
  created_at_ms: number;
  last_success_at_ms: number;
  last_success_revision?: string;
  last_failure_at_ms: number;
  last_failure_cause?: CloneCause;
  last_actor?: SourceActor;
}

export interface ForgeDescription {
  forge: SourceForge;
  host: string;
  grant_kind: SourceGrantKind;
  grant_label: string;
  permission: string;
  revoke_hint: string;
}

/** Response of `GET /api/v1/repo-connection-reads`. */
export interface CloneLedgerView {
  connection_id: string;
  records: CloneRecordView[] | null;
}

export interface CloneRecordView {
  record_id: string;
  repository: string;
  revision: string;
  actor: SourceActor;
  actor_id?: string;
  reason?: string;
  outcome: CloneOutcome;
  bytes: number;
  entries: number;
  duration_ms: number;
  at_ms: number;
}

/** Response of `POST /api/v1/repo-connection-revocations`. */
export interface RevocationView {
  connection_id: string;
  snapshots_deleted: number;
}

/** Response of `GET /api/v1/local-pairings`. */
export interface LocalPairingsView {
  pairings: PairingView[] | null;
  availability: LocalModeAvailability;
  command: string;
}

export interface PairingView {
  pairing_id: string;
  workflow_id: string;
  state: PairingState;
  user_code?: string;
  machine_name?: string;
  revision?: string;
  created_at_ms: number;
  claimed_at_ms?: number;
  expires_at_ms: number;
}

export interface LocalModeAvailability {
  deployments: string[] | null;
  available: boolean;
  why?: string;
}

/** Response of `GET /api/v1/assessments?workflow_id={id} and POST /api/v1/assessments`. */
export interface AssessmentView {
  assessment_id: string;
  workflow_id: string;
  source_revision: string;
  agent_config_hash: string;
  agent_config_hash_short: string;
  started_at_ms: number;
  completed_at_ms: number;
  spend_usd: number;
  spend_cap_usd: number;
  findings: FindingView[] | null;
  tally: Tally;
  partial: boolean;
  all_not_measured: boolean;
  reinferred?: boolean;
  diff?: AxisDiff[] | null;
}

export interface FindingView {
  axis: AssessmentAxis;
  state: AssessmentState;
  origin: AssessmentOrigin;
  claim: string;
  rank: number;
  evidence_surface: AssessmentEvidenceSurface;
  evidence_locator: string;
  evidence_path: string;
  missing_input?: AssessmentMissingInput;
  refusal_cause?: AssessmentRefusalCause;
  provider_model_version?: string;
  inference_address?: string;
  eval_set?: EvalSetReport | null;
  eval_set_cannot_fail?: boolean;
}

export interface EvalSetReport {
  eval_set_hash: string;
  score: Interval;
  n_cases: number;
  oracle_coverage: number;
  n_indecisive: number;
  coverage_measured: boolean;
  vacuous_dimensions?: string[] | null;
  cases: CaseView[] | null;
}

export interface Interval {
  mean: number;
  ci_low: number;
  ci_high: number;
  n_seeds: number;
}

export interface CaseView {
  case_id: string;
  suite?: string;
  oracle: OracleVerdict;
}

export interface OracleVerdict {
  decisive: boolean;
  kind: string;
  reason?: string;
}

export interface Tally {
  measured: number;
  observed: number;
  not_measured: number;
  refused: number;
  inferred: number;
}

export interface AxisDiff {
  axis: AssessmentAxis;
  before_state: AssessmentState;
  after_state: AssessmentState;
  before_origin: AssessmentOrigin;
  after_origin: AssessmentOrigin;
  before_claim: string;
  after_claim: string;
  before_provider_model_version?: string;
  after_provider_model_version?: string;
  cause: AssessmentDiffCause;
  why: string;
}

/** Response of `POST /api/v1/conversations`. */
export interface ConversationView {
  conversation_id: string;
  workflow_id: string;
  run_id: string;
  created_at: string;
  persistence: string;
}

/** Response of `POST /api/v1/conversation-turns`. */
export interface ConversationTurnView {
  turn_id: string;
  trace_id: string;
  first_message_id: number;
}

/** Response of `GET /api/v1/conversation-stream (event: message)`. */
export interface ConversationMessage {
  id: number;
  conversation_id: string;
  turn_id: string;
  kind: ConversationKind;
  provenance: ConversationProvenance;
  at: string;
  trace_id: string;
  plan?: PlanPayload | null;
  progress?: ProgressPayload | null;
  finding?: FindingPayload | null;
  proposal?: ProposalPayload | null;
  approval_request?: ApprovalRequestPayload | null;
  result?: ResultPayload | null;
  refusal?: RefusalPayload | null;
  answer?: AnswerPayload | null;
}

export interface PlanPayload {
  intent: ConversationIntent;
  steps: PlanStep[] | null;
  budget: BudgetEnvelope;
}

export interface PlanStep {
  id: string;
  title: string;
  surface: string;
}

export interface BudgetEnvelope {
  turn_ceiling: number;
  token_budget: number;
  tool_call_ceiling: number;
  wall_clock_seconds: number;
}

export interface ProgressPayload {
  phase: ConversationPhase;
  step_id: string;
  detail: string;
  elapsed_ms: number;
  remaining: BudgetRemaining;
}

export interface BudgetRemaining {
  turns: number;
  tokens: number;
  tool_calls: number;
  wall_clock_seconds: number;
}

export interface FindingPayload {
  surface: string;
  surface_href: string;
  axis: string;
  node: string;
  claim: string;
  evidence_ref: string;
  state: ConversationFindingState;
  missing_input: string;
  cause: string;
  source_revision: string;
}

export interface ProposalPayload {
  proposal_id: string;
  axis: string;
  node: string;
  delta_label: string;
  diff_ref: string;
  href: string;
}

export interface ApprovalRequestPayload {
  approval_id: string;
  proposal_id: string;
  action: string;
  blast_radius: string;
  reversible: string;
  approvable: boolean;
  unapprovable_reason: string;
}

export interface ResultPayload {
  run_id: string;
  stop_reason: StopReason;
  stopped_on_limit: boolean;
  stopped_at_step: string;
  reconciliation: ReconciliationEntry[] | null;
  summary: string;
  verified_claim: boolean;
  verdict_ref: string;
  delivery_ref: string;
  pull_request_url: string;
}

export interface ReconciliationEntry {
  step_id: string;
  state: ConversationStepState;
  reason: string;
}

export interface RefusalPayload {
  axis: string;
  node: string;
  cause: string;
  failure: ConversationFailureClass;
  can_do: string[] | null;
  surface_href: string;
  stop_reason: StopReason;
}

export interface AnswerPayload {
  text: string;
  topic: string;
}

/** Response of `GET /api/v1/conversation-stream (event: state) and GET /api/v1/conversation-trace`. */
export interface ConversationTurnState {
  turn_id: string;
  trace_id: string;
  intent: ConversationIntent;
  phase: ConversationPhase;
  envelope: BudgetEnvelope;
  remaining: BudgetRemaining;
  completed: Record<string, ConversationStepState>;
  terminal: boolean;
  stop_reason: StopReason;
  last_message_id: number;
}

