// Code generated by cmd/consoletypes. DO NOT EDIT.
//
// The console's data contract, generated from the Go view structs (docs/adr/ADR-007-console-type-generation.md).
//
// This file is CHECKED IN and regenerated in CI; a difference fails the build. That gate is the whole
// point: the failure mode of a hand-maintained type is not a compile error, it is a blank cell in
// production, because a field renamed in Go becomes `undefined` in TypeScript and renders as an
// em-dash that looks exactly like legitimately absent data.
//
// Two shapes to note, because they are contract facts rather than generator quirks:
//
//   `T[] | null`   a nil Go slice marshals as null, not []. The contract says so rather than
//                  pretending otherwise; a consumer that assumes an array fails exactly once, in
//                  production.
//   `T | null`     a pointer field is nullable. Null and ABSENT are different facts, and
//                  conflating them makes a UI render "absent" for a value the server called null.
//
// To change anything here: change the Go view struct, then run `make console-types`.

/** Response of `GET /api/p2/runs/{run_id}`. */
export interface RunView {
  run_id: string;
  config_hash: string;
  config_hash_display: string;
  source_revision: string;
  seed: number;
  status: string;
  halted_node_id?: string;
  halted_reason?: string;
  nodes: NodeView[] | null;
}

export interface NodeView {
  node_id: string;
  attempt_group: number;
  status: string;
  input_blob_hash?: string;
  output_blob_hash?: string;
  idempotency_key: string;
  error?: string;
}

/** Response of `GET /api/p2/transforms/{config_hash}/{source_revision}`. */
export interface TransformView {
  config_hash: string;
  config_hash_display: string;
  source_revision: string;
  status: string;
  verification_strength: string;
  requires_human_review: boolean;
  variant_branch?: string;
  variant_commit?: string;
  diff: string;
  diff_hash?: string;
  build_log?: string;
  rejected_node_id?: string;
  rejected_dimension?: string;
}

/** Response of `POST /api/p2/specs/submit`. */
export interface SubmitResult {
  config_hash: string;
  config_hash_display: string;
  source_revision: string;
  transform_status: string;
  variant_branch?: string;
  variant_commit?: string;
  diff_hash?: string;
  run_id?: string;
  rejected_node_id?: string;
  rejected_dimension?: string;
}

/** Response of `POST /api/p2/specs/{resolve,submit} (rejection)`. */
export interface SpecError {
  error: string;
  node_id?: string;
  dimension?: string;
  ref?: string;
}

/** Response of `GET /api/p25/runs/{run_id}/monitor`. */
export interface RunMonitor {
  run_id: string;
  config_hash: string;
  status: string;
  terminal: boolean;
  nodes: RunMonitorNode[] | null;
  halted?: RunMonitorHalted | null;
}

export interface RunMonitorNode {
  node_id: string;
  state: string;
  latency_ms: number;
  cost_usd: number;
  tokens_prompt: number;
  tokens_completion: number;
}

export interface RunMonitorHalted {
  node_id: string;
  reason: string;
}

/** Response of `GET /api/p35/workflows/{workflow_id}/graph`. */
export interface GraphView {
  workflow_id: string;
  ir_version: string;
  taxonomy_version: string;
  nodes: ViewNode[] | null;
  edges: ViewEdge[] | null;
  regions: ViewRegion[] | null;
  unclassified: ViewRegion[] | null;
  diagnostics?: Diagnostic[] | null;
  llm_calls: number;
}

export interface ViewNode {
  node_id: string;
  symbol: string;
  model: string;
  policy: string;
  tools: number;
  layer: number;
  order: number;
  labels: ViewLabel[] | null;
  region_ids: string[] | null;
}

export interface ViewLabel {
  pattern: string;
  ordinal: number;
  title: string;
  group: string;
  confidence: number;
  source: string;
  candidate: boolean;
  provenance: string;
  primary_metric: string;
  metrics: string[] | null;
}

export interface ViewEdge {
  from: string;
  to: string;
  kind: string;
}

export interface ViewRegion {
  subgraph_id: string;
  node_ids: string[] | null;
  labels: ViewLabel[] | null;
}

export interface Diagnostic {
  stage: string;
  subgraph_ref?: string;
  raw_pattern?: string;
  source?: string;
  reason: string;
}

/** Response of `GET /api/p4/workflows/{workflow_id}/board`. */
export interface BoardView {
  state: string;
  error?: string;
  workflow_id: string;
  eval_set_hash: string;
  profile: string;
  gate_set: string;
  profiles: string[] | null;
  progress: Progress;
  ranked: Row[] | null;
  disqualified: Row[] | null;
  pareto: ParetoPoint[] | null;
  coverage: CoverageView;
  spend: SpendReport;
  all_tie: boolean;
  notes?: string[] | null;
  unmeasured?: UnmeasuredView[] | null;
  runs_enqueued: number;
}

export interface Progress {
  units_planned: number;
  units_completed: number;
  seed_floor: number;
}

export interface Row {
  rank: number;
  variant_id: string;
  label: string;
  config_hash: string;
  config_hash_short: string;
  score: number;
  ci_low: number;
  ci_high: number;
  n_seeds: number;
  n_cases: number;
  method: string;
  components: ComponentView[] | null;
  penalties?: PenaltyView[] | null;
  gate_pass: boolean;
  failed_gates?: string[] | null;
  gate_reasons?: string[] | null;
  flags?: string[] | null;
  tied_with?: string[] | null;
  provisional: boolean;
}

export interface ComponentView {
  metric: string;
  role: string;
  raw: number;
  raw_ci_low: number;
  raw_ci_high: number;
  normalized: number;
  contribution: number;
  unit: string;
  judge?: JudgeStanding | null;
}

export interface JudgeStanding {
  metric: string;
  agreement: number;
  percent_agreement: number;
  n_human: number;
  floor: number;
  calibrated: boolean;
}

export interface PenaltyView {
  term: string;
  amount: number;
}

export interface ParetoPoint {
  variant_id: string;
  label: string;
  quality: number;
  cost_usd: number;
  latency_ms: number;
  non_dominated: boolean;
  composite: number;
}

export interface CoverageView {
  measured: boolean;
  dimensions: DimensionView[] | null;
  residual: ResidualItem[] | null;
  met: boolean;
  iterations: number;
  stopped_because?: string;
  n_cases: number;
  difficulty: number;
  difficulty_measured: boolean;
  diversity: number;
  oracle_coverage: number;
  n_oracle: number;
  n_indecisive: number;
  n_gold: number;
  n_weak: number;
  n_none: number;
  low_confidence: boolean;
  reasons?: string[] | null;
}

export interface DimensionView {
  name: string;
  achieved: number;
  target: number;
  covered: number;
  total: number;
  met: boolean;
  uncovered?: string[] | null;
  vacuous?: boolean;
}

export interface ResidualItem {
  id: string;
  dimension: string;
  kind: string;
  unreachable: boolean;
  reason: string;
}

export interface SpendReport {
  eval_run_id: string;
  by_kind: Record<string, number>;
  calls_by_kind: Record<string, number>;
  total_usd: number;
  budget: Budget;
  exhausted?: string[] | null;
}

export interface Budget {
  total_usd?: number | null;
  judge_usd?: number | null;
  generation_usd?: number | null;
  max_judge_calls?: number;
  max_generation_calls?: number;
}

export interface UnmeasuredView {
  variant_id: string;
  label: string;
  reason: string;
}

/** Response of `GET /api/p45/variants/{variant_id}/scorecard`. */
export interface ScorecardView {
  variant_id: string;
  eval_set_hash: string;
  config_hash: string;
  workflow_id: string;
  state: string;
  message?: string;
  overall: OverallMetrics;
  nodes: NodeRow[] | null;
  clusters: ClusterRow[] | null;
  diagnoses: DiagnosisCard[] | null;
  ablations: AblationCard[] | null;
  analyst: AnalystStatus;
  topology: TopologyView;
  partial: boolean;
  has_inconclusive: boolean;
  analyst_uncalibrated: boolean;
  classified_node_count: number;
  unclassified_node_count: number;
  read_only: boolean;
}

export interface OverallMetrics {
  task_success: number;
  n_cases: number;
  n_failing: number;
  cost_usd: number;
  latency_ms: number;
}

export interface NodeRow {
  node_id: string;
  failure_share: number;
  first_divergence_count: number;
  mean_cost_share: number;
  mean_latency_share: number;
  bottleneck_dimensions?: string[] | null;
  pattern?: string;
  classified: boolean;
}

export interface ClusterRow {
  signature: string;
  label: string;
  size: number;
  representative_case_id: string;
  member_case_ids: string[] | null;
}

export interface DiagnosisCard {
  code: string;
  description: string;
  node_id: string;
  source: string;
  confidence: number;
  evidence_case_ids: string[] | null;
  agreement: number;
  n_human: number;
  calibrated: boolean;
  analyst_flagged: boolean;
  low_confidence: boolean;
  classified: boolean;
}

export interface AblationCard {
  node_id: string;
  metric: string;
  delta_mean: number;
  ci_low: number;
  ci_high: number;
  n_seeds: number;
  verdict: string;
}

export interface AnalystStatus {
  present: boolean;
  agreement: number;
  n_human: number;
  calibrated: boolean;
  floor: number;
  flagged: boolean;
}

export interface TopologyView {
  edges: EdgeView[] | null;
  ordered_by_topology: boolean;
  provenance?: string;
}

export interface EdgeView {
  from: string;
  to: string;
  provenance: string;
  signal: string;
  confidence: number;
}

/** Response of `GET /api/p55/workflows/{workflow_id}/surface`. */
export interface ProposalSurface {
  workflow_id: string;
  automation_level: string;
  state: string;
  error?: string;
  recommendations: Card[] | null;
  withheld: Card[] | null;
  trend: TrendView;
}

export interface Card {
  proposal_id: string;
  operator: string;
  node_id: string;
  pattern: string;
  diag_id: string;
  evidence_case_ids: string[] | null;
  rationale: string;
  source_diff: string;
  spec_diff: DimChange[] | null;
  build_status: string;
  state: string;
  gate_result: string;
  held_out: boolean;
  held_out_label: string;
  delta: number;
  ci_low: number;
  ci_high: number;
  significant: boolean;
  cost_delta: number;
  latency_delta: number;
  cases_fixed: string[] | null;
  cases_broken: string[] | null;
  narration: string;
  can_open_pr: boolean;
  pr_disabled_reason?: string;
}

export interface DimChange {
  node_id: string;
  dimension: string;
  from: string;
  to: string;
}

export interface TrendView {
  points: TrendPoint[] | null;
  globally_improved: boolean;
  problems_moved: boolean;
  narrative: string;
}

export interface TrendPoint {
  variant_id: string;
  iteration: number;
  overall_success: number;
  cluster_sizes: Record<string, number>;
}

/** Response of `POST /api/p55/workflows/{workflow_id}/proposals/{proposal_id}/open-pr`. */
export interface PRResult {
  proposal_id: string;
  branch: string;
  url: string;
  draft: boolean;
  rollback: string;
}

/** Response of `GET /api/p7/customers/{customer_id}/billing`. */
export interface BillingView {
  customer_id: string;
  period: string;
  available_periods?: string[] | null;
  sum: number;
  sum_unit: string;
  sum_trend?: PeriodPoint[] | null;
  link_coverage?: LinkCoverageView | null;
  meters: MeterView[] | null;
  plan_id: string;
  plan_name: string;
  plan_config_version: string;
  entitlements: EntitlementRow[] | null;
  invoice: InvoiceView;
  state: BillingStateView;
  savings: SavingsView;
  denial?: DenialView | null;
  drift?: DriftView[] | null;
  empty: boolean;
}

export interface PeriodPoint {
  period: string;
  sum: number;
  baseline_sum: number;
  optimized_sum: number;
}

export interface LinkCoverageView {
  runs_linked: number;
  runs_reported: number;
  known: boolean;
  complete: boolean;
}

export interface MeterView {
  metric: string;
  label: string;
  value: number;
  unit: string;
  allowed: number;
  unlimited: boolean;
  over: boolean;
  reported_to_provider: boolean;
  provider_usage_ref?: string;
}

export interface EntitlementRow {
  feature: string;
  label: string;
  included: boolean;
  reason?: string;
  upgrade_plan?: string;
  upgrade_plan_name?: string;
}

export interface InvoiceView {
  invoice_ref?: string;
  status?: string;
  lines: LineView[] | null;
  totals?: TotalView[] | null;
}

export interface LineView {
  kind: string;
  label: string;
  basis: string;
  amount_ref?: string;
  quantity: number;
  unit?: string;
  charge_ref?: string;
  evidence?: EvidenceView[] | null;
  corrects?: string;
}

export interface EvidenceView {
  kind: string;
  ref: string;
  label: string;
  link?: string;
  method?: MethodView | null;
}

export interface MethodView {
  id: string;
  eval_set_hash: string;
  holdout_cases: number;
  generating_cases: number;
  seeds: number;
  baseline_config_hash: string;
  candidate_config_hash: string;
  significance_note?: string;
}

export interface TotalView {
  kind: string;
  label: string;
  lines: number;
  quantity: number;
}

export interface BillingStateView {
  invoice_status?: string;
  subscription_status?: string;
  payment_failed: boolean;
  past_due: boolean;
  guidance?: string;
}

export interface SavingsView {
  gainshare_consent: boolean;
  consented_at?: string;
  consent_available: boolean;
  baseline_sum: number;
  optimized_sum: number;
  verified_savings: number;
  unit: string;
  billed?: SavingRow[] | null;
  excluded?: ExcludedRow[] | null;
  none_verified: boolean;
}

export interface SavingRow {
  ref: string;
  baseline_sum: number;
  optimized_sum: number;
  savings: number;
  merge_commit: string;
  method?: MethodView | null;
}

export interface ExcludedRow {
  ref: string;
  reason: string;
  would_have_been: number;
}

export interface DenialView {
  feature: string;
  feature_label: string;
  reason: string;
  reason_code: string;
  upgrade_plan?: string;
  upgrade_plan_name?: string;
  limit?: DenialLimitView | null;
}

export interface DenialLimitView {
  limit: string;
  label: string;
  allowed: number;
  observed: number;
  period: string;
}

export interface DriftView {
  kind: string;
  metric: string;
  detail: string;
  platform_quantity: number;
  provider_quantity: number;
}

/** Response of `GET /api/p21/customers/{customer_id}/payment`. */
export interface PaymentView {
  billing: BillingView;
  plans: PlanOptionView[] | null;
  payment_method: PaymentMethodView;
  collection_available: boolean;
  unavailable?: BillingUnavailableView | null;
}

export interface PlanOptionView {
  plan_id: string;
  name: string;
  rank: number;
  current: boolean;
  direction: string;
  subscribable: boolean;
}

export interface PaymentMethodView {
  present: boolean;
  brand?: string;
  last4?: string;
  status?: string;
  reason?: string;
  restore_path?: string;
}

export interface BillingUnavailableView {
  detail: string;
  retryable: boolean;
}

/** Response of `POST /api/p21/customers/{customer_id}/checkout-session`. */
export interface CheckoutView {
  url?: string;
  client_secret?: string;
  session_ref?: string;
  expires_at?: string;
}

/** Response of `POST /api/p21/customers/{customer_id}/plan`. */
export interface PlanChangeView {
  plan_id: string;
  plan_name: string;
  status?: string;
  changed: boolean;
  checkout_required: boolean;
}

/** Response of `GET /api/p12/deliveries`. */
export interface DeliveriesView {
  deliveries: DeliveryView[] | null;
  route: RouteConditionView;
}

export interface DeliveryView {
  delivery_id: string;
  state: string;
  config_hash: string;
  source_revision: string;
  target: string;
  mode: string;
  forge_ref: string;
  reason?: string;
  merge_commit?: string;
  proposal_ref: string;
}

export interface RouteConditionView {
  kind: string;
  detail?: string;
  next_action?: string;
  targets?: string[] | null;
}

