// Command p4boarddemo stands up the P4 eval board against a LIVE fan-out with a stubbed provider.
//
// It is the e2e driver for task 8.7, and it is deliberately a real pipeline rather than a fixture
// dump: the eval set is generated by the gap-filling loop, the runs go through the bounded worker
// pool, the traces are real telemetry spans, the evaluators score those spans, the results land in
// the tagged store, the statistics come from the multi-seed bootstrap, and the board is the computed
// view over the score cache. The ONLY stub is the provider — everything between the queue and the
// pixel is the shipped code path.
//
// That distinction matters. A demo that fabricated a board would prove the HTML parses; this one
// proves the measurement path produces a board.
//
//	go run ./cmd/p4boarddemo        # then open http://127.0.0.1:8085/p4/board?workflow=wf-router
package main

import (
	"context"
	"encoding/json"
	"flag"
	"fmt"
	"log"
	"math/rand"
	"net/http"
	"os"
	"sync"
	"time"

	"github.com/heros-foreal/agentd/internal/api"
	"github.com/heros-foreal/agentd/internal/config"
	"github.com/heros-foreal/agentd/internal/discovery"
	"github.com/heros-foreal/agentd/internal/evalboard"
	"github.com/heros-foreal/agentd/internal/evalgen"
	"github.com/heros-foreal/agentd/internal/evalharness"
	"github.com/heros-foreal/agentd/internal/evalrun"
	"github.com/heros-foreal/agentd/internal/evalstats"
	"github.com/heros-foreal/agentd/internal/patternclassifier"
	"github.com/heros-foreal/agentd/internal/runqueue"
	"github.com/heros-foreal/agentd/internal/scoring"
	"github.com/heros-foreal/agentd/internal/telemetry"
)

func main() {
	addr := flag.String("addr", "127.0.0.1:8085", "listen address")
	seeds := flag.Int("seeds", 5, "seeds per case")
	extra := flag.Int("extra-variants", 0,
		"additional variants to measure, for exercising the board's virtualization at scale")
	irPath := flag.String("ir", "",
		"path to a Workflow IR emitted by `discover` over a REAL repo; omit to use the built-in fixture")
	flag.Parse()
	variants := demoVariants()
	variants = append(variants, syntheticVariants(*extra)...)

	ctx := context.Background()

	// The fixture IR proves the measurement path and nothing about any real codebase. Pointing --ir
	// at real discovery output is what makes the board about a real workflow.
	ir := demoIR()
	walk := fixtureWalk
	prober := evalgen.Prober(&simRuntime{reachable: map[string]bool{"branch_a": true, "branch_b": true}})
	seed := seedCases()
	caseModel := evalgen.CaseModel(&scriptedGenerator{})

	if *irPath != "" {
		loaded, res, account, err := loadRealIR(ctx, *irPath)
		if err != nil {
			log.Fatalf("load IR: %v", err)
		}
		writeBackLabels(loaded, res)
		ir = loaded
		fmt.Println(account)

		// Swap the ENTIRE runtime, not just the IR. Leaving the fixture's prober and walk in place
		// while handing them a foreign IR is what made the previous run's node-scoped numbers a
		// measurement of this harness rather than of that workflow.
		walk = irWalk(ir)
		prober = irProber{walk: walk}
		seed = irSeedCases(ir, 2)
		caseModel = irCaseGenerator{ir: ir}
	}

	// ── 1. Generate the eval set with the real gap-filling loop ──────────────────
	loopCfg := evalgen.DefaultLoopConfig(caseModel)
	res, err := evalgen.Fill(ctx, ir, seed, prober, loopCfg)
	if err != nil {
		log.Fatalf("eval-set generation: %v", err)
	}
	// Difficulty is MEASURED against a baseline, not asserted.
	cases, err := evalgen.MeasureDifficulty(ctx, &baseline{}, res.Cases, 3)
	if err != nil {
		log.Fatalf("difficulty: %v", err)
	}
	quality := evalgen.MeasureQuality(cases, loopCfg)

	set, err := evalrun.NewEvalSet(ir.Workflow.ID, ir.IRVersion, cases)
	if err != nil {
		log.Fatalf("eval set: %v", err)
	}
	fmt.Printf("eval set %s: %d cases · %s · stopped: %s\n",
		set.Hash[:12], len(set.Cases), res.Report.Summary(), res.StoppedBecause)

	// Adversarial cases are routed to the sandbox before anything executes.
	placements := evalrun.AuditPlacements(set.Cases)
	if bad := evalrun.UnsandboxedAdversarial(placements, set.Cases); len(bad) != 0 {
		log.Fatalf("refusing to run: adversarial cases scheduled on the host: %v", bad)
	}
	sandboxed := 0
	for _, p := range placements {
		if p.Sandboxed {
			sandboxed++
		}
	}
	fmt.Printf("placement: %d of %d cases routed to the P3 sandbox\n", sandboxed, len(placements))

	// ── 2. Fan out every variant over the set, through the bounded worker pool ────
	// The budget scales with the sweep. It is still a CAP — the earlier fixed $50 stopped an
	// 84-variant sweep two thirds of the way through, which is the cap working correctly and is
	// exactly how the board's partial state got exercised for real.
	budget := 20.0 + 3.0*float64(len(variants))
	meter := evalrun.NewMeter("evalrun-demo", evalrun.Budget{TotalUSD: &budget})
	store := evalrun.NewMemStore()
	registry := evalharness.NewBuiltinRegistry()

	planned, completed := 0, 0
	for _, v := range variants {
		units := evalrun.PlanUnits(v.id, v.configHash, "rev-1", set, seedList(*seeds))
		planned += len(units)

		q := newMemQueue(units)
		handler := &runHandler{
			variant:  v,
			set:      set,
			registry: registry,
			store:    store,
			meter:    meter,
			ir:       ir,
			walk:     walk,
		}
		pool, err := evalrun.NewPool(q, handler, evalrun.PoolConfig{
			Concurrency:  8,
			PollInterval: time.Millisecond,
		})
		if err != nil {
			log.Fatalf("pool: %v", err)
		}
		stats, err := pool.Drain(ctx)
		if err != nil {
			log.Fatalf("drain %s: %v", v.id, err)
		}
		completed += stats.Handled
		fmt.Printf("variant %-16s %3d units · peak in-flight %d · %d failed\n",
			v.id, stats.Handled, stats.MaxInFlight, stats.Failed)
	}
	fmt.Printf("fan-out: %d/%d units · %d result rows · spend $%.4f\n",
		completed, planned, store.Len(), meter.Report().TotalUSD)

	// ── 3. Build the score cache once ────────────────────────────────────────────
	board := scoring.Board{EvalSetHash: set.Hash, Specs: scoring.DefaultSpecs()}
	labels := map[string]string{}
	for _, v := range variants {
		labels[v.id] = v.label
		variant := scoring.Variant{
			VariantID:     v.id,
			ConfigHash:    v.configHash,
			Label:         v.label,
			Providers:     v.providers,
			Metrics:       map[string]evalstats.Series{},
			WeakCaseIDs:   set.WeakCaseIDs(),
			LowConfidence: quality.LowConfidence,
		}
		for _, spec := range scoring.DefaultSpecs() {
			s, err := store.SeriesFor(ctx, set.Hash, v.id, spec.Name)
			if err != nil {
				log.Fatalf("series: %v", err)
			}
			variant.Metrics[spec.Name] = s
		}
		board.Variants = append(board.Variants, variant)
	}
	cache, err := scoring.Build(board, evalstats.DefaultConfig())
	if err != nil {
		log.Fatalf("score cache: %v", err)
	}

	// ── 4. Serve the board ───────────────────────────────────────────────────────
	src := &boardSource{
		workflowID: ir.Workflow.ID,
		cache:      cache,
		coverage:   res.Report,
		quality:    quality,
		stopped:    res.StoppedBecause,
		spend:      meter.Report(),
		labels:     labels,
		progress:   evalboard.Progress{UnitsPlanned: planned, UnitsCompleted: completed, SeedFloor: *seeds},
		gates: scoring.GateSet{
			Name:          "production",
			MinQuality:    fptr(0.55),
			MaxCostPerRun: fptr(0.20),
			LatencySLAMs:  fptr(4000),
		},
	}

	srv := api.New(nil, config.Config{})
	srv.MountP4(src)
	fmt.Printf("\n  open http://%s/p4/board?workflow=%s\n\n", *addr, ir.Workflow.ID)
	if err := http.ListenAndServe(*addr, srv.Handler); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}

func fptr(v float64) *float64 { return &v }

func seedList(n int) []int64 {
	out := make([]int64, 0, n)
	for i := 0; i < n; i++ {
		out = append(out, int64(i))
	}
	return out
}

// ─────────────────────────────────────────────────────────────────────────────
// The board source
// ─────────────────────────────────────────────────────────────────────────────

type boardSource struct {
	workflowID string
	cache      *scoring.Cache
	coverage   evalgen.CoverageReport
	quality    evalgen.SetQuality
	stopped    string
	spend      evalrun.SpendReport
	labels     map[string]string
	progress   evalboard.Progress
	gates      scoring.GateSet
}

// Board re-ranks from the CACHE. Switching profiles enqueues nothing — the source holds no queue and
// no executor, so that is structural rather than a promise.
func (s *boardSource) Board(workflowID, profile string) (evalboard.View, bool) {
	// An unknown workflow is NOT this workflow's board with a different title. Returning the board
	// anyway would make the 404 path unreachable and untested, and would show a user someone else's
	// numbers under their own workflow id.
	if workflowID != s.workflowID {
		return evalboard.View{}, false
	}
	p, ok := scoring.NamedProfiles()[profile]
	if !ok {
		p = scoring.Balanced()
	}
	return evalboard.Build(evalboard.Input{
		WorkflowID:     workflowID,
		Cache:          s.cache,
		Profile:        p,
		Gates:          s.gates,
		Coverage:       &s.coverage,
		Quality:        &s.quality,
		StoppedBecause: s.stopped,
		Spend:          s.spend,
		Progress:       s.progress,
		Labels:         s.labels,
	}), true
}

// ─────────────────────────────────────────────────────────────────────────────
// Variants
// ─────────────────────────────────────────────────────────────────────────────

type demoVariant struct {
	id, label, configHash string
	providers             []string
	// quality is the probability this configuration answers a case correctly.
	quality float64
	// costPerNode / latencyPerNode shape the stubbed provider's per-call figures.
	costPerNode, latencyPerNode float64
}

// demoVariants is chosen to exercise every board state at once: a strong-but-slow one, a balanced
// one, a cheap-but-below-quality one that the gate must DISQUALIFY, and a near-duplicate of the
// balanced one so the board has a genuine TIE to render.
func demoVariants() []demoVariant {
	return []demoVariant{
		{id: "v-sonnet-rich", label: "sonnet + rich context", configHash: hash64("sonnet-rich"),
			providers: []string{"anthropic"}, quality: 0.93, costPerNode: 0.012, latencyPerNode: 620},
		{id: "v-balanced", label: "haiku + summarized context", configHash: hash64("balanced"),
			providers: []string{"anthropic"}, quality: 0.78, costPerNode: 0.004, latencyPerNode: 280},
		{id: "v-balanced-alt", label: "haiku + sliding window", configHash: hash64("balanced-alt"),
			providers: []string{"anthropic"}, quality: 0.775, costPerNode: 0.0041, latencyPerNode: 285},
		{id: "v-cheap-broken", label: "haiku + no context", configHash: hash64("cheap-broken"),
			providers: []string{"anthropic"}, quality: 0.34, costPerNode: 0.001, latencyPerNode: 140},
	}
}

// syntheticVariants produces n additional REAL variants — each one is measured by the same fan-out
// over the same eval set as the four hand-chosen ones. They exist to put a many-row board in front
// of the virtualization, and they are measured rather than fabricated for the same reason the demo
// stubs only the provider: a board of invented rows would prove the table scrolls, not that the
// measurement path scales.
func syntheticVariants(n int) []demoVariant {
	out := make([]demoVariant, 0, n)
	for i := 0; i < n; i++ {
		id := fmt.Sprintf("v-sweep-%03d", i)
		out = append(out, demoVariant{
			id:             id,
			label:          fmt.Sprintf("sweep %03d (temp %.2f)", i, 0.1+float64(i%10)*0.08),
			configHash:     hash64(id),
			providers:      []string{"anthropic"},
			quality:        0.55 + float64(i%35)/100,
			costPerNode:    0.002 + float64(i%12)*0.0009,
			latencyPerNode: 180 + float64(i%15)*40,
		})
	}
	return out
}

func hash64(seed string) string {
	const hex = "0123456789abcdef"
	out := make([]byte, 64)
	for i := range out {
		out[i] = hex[(int(seed[i%len(seed)])*7+i*3)%16]
	}
	return string(out)
}

// ─────────────────────────────────────────────────────────────────────────────
// The run handler — stubbed provider, real everything else
// ─────────────────────────────────────────────────────────────────────────────

type runHandler struct {
	variant  demoVariant
	set      evalrun.EvalSet
	registry *evalharness.Registry
	store    *evalrun.MemStore
	meter    *evalrun.Meter
	ir       *discovery.IR
	// walk returns the node ids one case executes, in order. It is a FIELD rather than hardcoded
	// because the fixture's topology and a real repo's are different topologies: with the fixture
	// baked in, handing the runner a real IR produced traces for nodes that repo does not have, and
	// every node-scoped number was therefore about the fixture wearing the real workflow's name.
	walk func(c evalharness.Case) []string
}

// Handle executes one {variant, case, seed}: it produces a trace the way the P2.5 instrument would,
// scores it with the real evaluators, and persists fully-tagged rows.
func (h *runHandler) Handle(ctx context.Context, item runqueue.Item) error {
	caseID, ok := caseOf(item.RunID, h.set, h.variant.configHash)
	if !ok {
		return fmt.Errorf("no case for run %s", item.RunID)
	}
	c, _ := h.set.CaseByID(caseID)

	rc := telemetry.RunContext{
		VariantID:  h.variant.id,
		RunID:      item.RunID,
		ConfigHash: h.variant.configHash,
		Seed:       item.Seed,
		CaseID:     caseID,
	}

	tr, cost := h.stubProviderRun(rc, c)
	if err := h.meter.Charge(evalrun.SpendExecution, cost); err != nil {
		return err
	}

	values, err := evalharness.RunMetrics(ctx, h.registry, tr, c)
	if err != nil {
		return err
	}
	values = append(values, evalharness.ContributionMetrics(tr, c)...)

	// The pattern is read off the node this case actually walked. Hardcoding "router" here meant a
	// real IR (whose nodes are named nothing like the fixture's) got an empty pattern on every row.
	pattern := ""
	if walked := h.walk(c); len(walked) > 0 {
		if p, _ := evalharness.NodePattern(h.ir, walked[0]); p != "" {
			pattern = string(p)
		}
	}
	rows := evalrun.ResultsFrom(rc, h.ir.Workflow.ID, h.set.Hash, c, pattern, values, time.Now())
	return h.store.PutResults(ctx, rows)
}

// stubProviderRun is THE stub, and the only one: it emits the spans a real provider call would,
// with per-seed variation so the multi-seed statistics have something real to measure.
func (h *runHandler) stubProviderRun(rc telemetry.RunContext, c evalharness.Case) (evalharness.Trace, float64) {
	// Deterministic per {variant, case, seed}: the demo must render the same board twice.
	rng := rand.New(rand.NewSource(int64(len(rc.ConfigHash)) + rc.Seed*7919 + int64(len(c.CaseID))*104729 +
		int64(c.CaseID[len(c.CaseID)-1])))

	nodes := h.walk(c)

	tr := evalharness.Trace{NodeOutputs: map[string]json.RawMessage{}, NodeInputs: map[string]json.RawMessage{}}
	var spans []telemetry.Span
	now := time.Now()
	var totalCost float64

	for i, node := range nodes {
		cost := h.variant.costPerNode * (0.85 + rng.Float64()*0.3)
		latency := h.variant.latencyPerNode * (0.8 + rng.Float64()*0.4)
		totalCost += cost
		start := now.Add(time.Duration(i) * time.Duration(latency) * time.Millisecond)
		spans = append(spans, telemetry.Span{
			TraceID:   telemetry.TraceID(rc.RunID),
			SpanID:    telemetry.NodeSpanID(rc.RunID + ":" + node + ":" + fmt.Sprint(i)),
			Kind:      telemetry.SpanKindNode,
			Name:      "chat " + node,
			StartTime: start,
			EndTime:   start.Add(time.Duration(latency) * time.Millisecond),
			Status:    telemetry.SpanStatusOK,
			Attributes: map[string]any{
				telemetry.AttrNodeID:           node,
				telemetry.AttrRunID:            rc.RunID,
				telemetry.AttrVariantID:        rc.VariantID,
				telemetry.AttrConfigHash:       rc.ConfigHash,
				telemetry.AttrCaseID:           rc.CaseID,
				telemetry.AttrSeed:             rc.Seed,
				telemetry.AttrCostUSD:          cost,
				telemetry.AttrLatencyMS:        latency,
				telemetry.AttrNodeFailed:       false,
				telemetry.AttrGenAIUsageInput:  200 + rng.Intn(120),
				telemetry.AttrGenAIUsageOutput: 80 + rng.Intn(60),
			},
		})
	}
	tr.Trace = telemetry.Trace{Run: rc, Spans: spans}

	// The answer: correct with the variant's quality probability. This is what makes the eval set
	// discriminating — a stub that always answered correctly would produce a board of perfect ties.
	if rng.Float64() < h.variant.quality {
		tr.Output = json.RawMessage(`{"a":"correct"}`)
	} else {
		tr.Output = json.RawMessage(`{"a":"wrong"}`)
	}
	return tr, totalCost
}

// fixtureWalk is the built-in demo workflow's topology: router -> chosen branch -> N reflect turns.
func fixtureWalk(c evalharness.Case) []string {
	var in map[string]any
	_ = json.Unmarshal(c.Input, &in)
	route := "branch_a"
	if r, _ := in["route"].(string); r == "branch_b" {
		route = "branch_b"
	}
	turns := 1
	if t, ok := in["turns"].(float64); ok && int(t) > 0 {
		turns = int(t)
	}
	return append([]string{"router", route}, repeat("reflect", turns)...)
}

func repeat(s string, n int) []string {
	out := make([]string, 0, n)
	for i := 0; i < n; i++ {
		out = append(out, s)
	}
	return out
}

// caseOf recovers which case a run id belongs to by re-deriving the id — the same content-derived
// function that produced it, which is what makes the mapping unambiguous.
func caseOf(runID string, set evalrun.EvalSet, configHash string) (string, bool) {
	for _, c := range set.Cases {
		for seed := int64(0); seed < 32; seed++ {
			if evalrun.RunIDFor(configHash, "rev-1", c.CaseID, seed) == runID {
				return c.CaseID, true
			}
		}
	}
	return "", false
}

// ─────────────────────────────────────────────────────────────────────────────
// In-memory queue (the demo does not require Postgres)
// ─────────────────────────────────────────────────────────────────────────────

type memQueue struct {
	mu     sync.Mutex
	ready  []runqueue.Item
	leased map[string]bool
}

func newMemQueue(units []evalrun.Unit) *memQueue {
	q := &memQueue{leased: map[string]bool{}}
	for _, u := range units {
		q.ready = append(q.ready, runqueue.Item{
			RunID: u.RunID, ConfigHash: u.ConfigHash, SourceRevision: u.SourceRevision, Seed: u.Seed,
		})
	}
	return q
}

func (q *memQueue) Dequeue(context.Context, string) (*runqueue.Item, error) {
	q.mu.Lock()
	defer q.mu.Unlock()
	if len(q.ready) == 0 {
		return nil, runqueue.ErrEmpty
	}
	it := q.ready[0]
	q.ready = q.ready[1:]
	q.leased[it.RunID] = true
	return &it, nil
}

func (q *memQueue) Ack(_ context.Context, runID, _ string) error {
	q.mu.Lock()
	defer q.mu.Unlock()
	delete(q.leased, runID)
	return nil
}

func (q *memQueue) Nack(_ context.Context, runID, _ string, _ error, _ time.Duration) error {
	q.mu.Lock()
	defer q.mu.Unlock()
	delete(q.leased, runID)
	return nil
}

func (q *memQueue) Renew(context.Context, string, string) error { return nil }

// ─────────────────────────────────────────────────────────────────────────────
// Fixtures: the multi-pattern workflow, the generator seam, the baseline
// ─────────────────────────────────────────────────────────────────────────────

// demoIR is the task 8.1 fixture: Routing -> per-branch Tool Use -> Reflection.
func demoIR() *discovery.IR {
	node := func(id string, p patternclassifier.Pattern) discovery.IRNode {
		return discovery.IRNode{
			NodeID: id, Kind: "static_definition",
			PatternLabels: []discovery.IRPatternLabel{{
				Pattern:         string(p),
				Confidence:      patternclassifier.ConfidenceTopologyDetermined,
				Source:          string(patternclassifier.SourceRule),
				DetectorID:      "demo",
				TaxonomyVersion: patternclassifier.TaxonomyVersion,
			}},
			IOContract: discovery.IRIOContract{
				InputSchema: map[string]any{
					"type": "object", "required": []any{"route", "q"},
					"properties": map[string]any{
						"route": map[string]any{"type": "string"},
						"q":     map[string]any{"type": "string"},
						"turns": map[string]any{"type": "integer"},
					},
				},
				OutputSchema: map[string]any{
					"type": "object", "required": []any{"a"},
					"properties": map[string]any{"a": map[string]any{"type": "string"}},
				},
			},
		}
	}
	return &discovery.IR{
		IRVersion: discovery.IRVersionPatternLabels,
		Workflow:  discovery.IRWorkflow{ID: "wf-router", Language: "python"},
		Nodes: []discovery.IRNode{
			node("router", patternclassifier.Routing),
			node("branch_a", patternclassifier.ToolUse),
			node("branch_b", patternclassifier.ToolUse),
			node("reflect", patternclassifier.Reflection),
		},
		Edges: []discovery.IREdge{
			{FromNodeID: "router", ToNodeID: "branch_a", Kind: "control"},
			{FromNodeID: "router", ToNodeID: "branch_b", Kind: "control"},
			{FromNodeID: "branch_a", ToNodeID: "reflect", Kind: "data"},
			{FromNodeID: "branch_b", ToNodeID: "reflect", Kind: "data"},
			{FromNodeID: "reflect", ToNodeID: "reflect", Kind: "control"},
		},
	}
}

// seedCases is the hand-authored starting set the loop fills gaps around.
func seedCases() []evalharness.Case {
	mk := func(id, route, q string, turns int) evalharness.Case {
		in, _ := json.Marshal(map[string]any{"route": route, "q": q, "turns": turns})
		ref, _ := json.Marshal(map[string]any{"a": "correct"})
		return evalharness.Case{
			CaseID: id, WorkflowID: "wf-router", Suite: "hand",
			Input: in, Reference: ref, Label: evalharness.LabelGold,
			Origin: evalharness.OriginHandAuthored,
		}
	}
	return []evalharness.Case{
		mk("hand-1", "branch_a", "summarize the quarterly revenue report", 1),
		mk("hand-2", "branch_b", "look up the shipping status for order 4471", 2),
	}
}

// simRuntime is the coverage prober: it interprets a case the way the fixture workflow would and
// emits real spans, so coverage is derived by the production TraceEvidence path.
type simRuntime struct{ reachable map[string]bool }

func (p *simRuntime) Probe(_ context.Context, ir *discovery.IR, c evalharness.Case) (evalgen.Evidence, error) {
	var in map[string]any
	_ = json.Unmarshal(c.Input, &in)
	route, _ := in["route"].(string)
	if !p.reachable[route] {
		route = "branch_a"
	}
	turns := 1
	if t, ok := in["turns"].(float64); ok && int(t) > 0 {
		turns = int(t)
	}
	if turns > 8 {
		turns = 8
	}
	var spans []telemetry.Span
	add := func(node string, i int) {
		spans = append(spans, telemetry.Span{
			TraceID: telemetry.TraceID(c.CaseID), Kind: telemetry.SpanKindNode,
			SpanID:     telemetry.NodeSpanID(c.CaseID + node + fmt.Sprint(i)),
			Status:     telemetry.SpanStatusOK,
			Attributes: map[string]any{telemetry.AttrNodeID: node},
		})
	}
	add("router", 0)
	add(route, 1)
	for i := 0; i < turns; i++ {
		add("reflect", 2+i)
	}
	return evalgen.TraceEvidence(ir, c.CaseID, telemetry.Trace{Spans: spans}), nil
}

// scriptedGenerator stands in for the LLM case generator. It answers the targets it is handed, which
// is the property under demonstration: the expensive layer is pointed at the residual, not sprayed.
type scriptedGenerator struct{}

func (scriptedGenerator) GenerateCases(_ context.Context, req evalgen.CaseRequest) ([]evalgen.GeneratedCase, error) {
	var out []evalgen.GeneratedCase
	for _, target := range req.Targets {
		route, turns := "branch_a", 1
		if _, to, ok := evalgen.ParseEdgeID(target); ok && (to == "branch_a" || to == "branch_b") {
			route = to
		}
		if _, outcome, ok := evalgen.ParseBranchID(target); ok && (outcome == "branch_a" || outcome == "branch_b") {
			route = outcome
		}
		if node, bound, ok := evalgen.ParseLoopBoundID(target); ok && node == "reflect" {
			turns = evalgen.DefaultLoopBounds[bound]
		}
		in, _ := json.Marshal(map[string]any{"route": route, "q": "targeted case for " + target, "turns": turns})
		// A real LLM generator writes an expected answer. It is UNREVIEWED, so the layer labels it
		// weak — and a set whose cases carry no oracle at all is one whose quality number rests on a
		// handful of cases, which the oracle-coverage floor now catches.
		ref, _ := json.Marshal(map[string]any{"a": "correct"})
		out = append(out, evalgen.GeneratedCase{Input: in, Reference: ref, Targets: []string{target}})
	}
	for _, k := range req.EdgeCases {
		in, _ := json.Marshal(map[string]any{"route": "branch_a", "q": "edge case " + string(k), "turns": 1})
		ref, _ := json.Marshal(map[string]any{"a": "correct"})
		out = append(out, evalgen.GeneratedCase{Input: in, Reference: ref, EdgeCase: k, Targets: []string{string(k)}})
	}
	return out, nil
}

// baseline measures case difficulty: it passes the short, ordinary cases and struggles with the
// edge-case slots, which is what gives the set a non-zero measured difficulty.
type baseline struct {
	mu sync.Mutex
	n  int
}

func (b *baseline) Pass(_ context.Context, c evalharness.Case) (bool, error) {
	b.mu.Lock()
	defer b.mu.Unlock()
	b.n++
	switch c.EdgeCase {
	case evalharness.EdgeCaseNone:
		return b.n%5 != 0, nil
	case evalharness.EdgeCaseBoundary, evalharness.EdgeCaseMalformedInput:
		return b.n%3 == 0, nil
	default:
		return b.n%4 == 0, nil
	}
}
