package transform

import (
	"fmt"
	"go/format"
	"sort"
	"strings"

	"github.com/heros-foreal/agentd/internal/discovery"
	"github.com/heros-foreal/agentd/internal/typedcontract"
	"github.com/heros-foreal/agentd/internal/variantspec"
)

// This file is the codemod-emission half of the fixed typed adapter catalog (task 2.1). §1
// (internal/typedcontract) owns MATCHING — "does a catalog adapter bridge this edge, and what is its
// typed shape". Here each catalog kind EMITS a deterministic, AST-valid source change: the adapter
// node's own code, a pure function over the producer's output shape. This is the ADR-001 realisation of
// "adapter auto-insertion is a generated code change, never a hidden runtime coercion" (task 2.2).
//
// # Why generated source, and why it is a pure function of the spec
//
// The adapter is a real, inspectable change to data flow. Emitting it as source — rather than resolving
// it in a runtime shim — is what makes it reviewable in a diff and revertible with `git revert`
// (Decision 8). The emitter is a PURE FUNCTION of the InsertedAdapter, so the same spec yields
// byte-identical source on every regeneration (task 2.4's determinism), and it is run through
// go/format so formatting can never drift.
//
// # Go only, and it says so
//
// The strong emission path is Go, the language whose engine (engines.go) carries real type structure.
// A non-Go target is REFUSED with a named reason rather than emitting a lie in the wrong syntax — the
// same fail-loud stance engineFor takes. The fixed catalog is not free-form LLM transform code (which
// would need P3 sandboxing + P5.5 verification, out of scope); it is these five deterministic shapes.

// GeneratedFile is one emitted source file: its repo-relative path and its bytes. The path is
// deterministic (derived from the adapter node id) so regeneration overwrites, never duplicates.
type GeneratedFile struct {
	Path    string
	Content []byte
}

// AdapterPackageDir is where generated adapter sources live in the target tree. A dedicated directory
// keeps generated code out of the user's hand-written files (so a `git revert` of the adapter is
// surgical) and makes the inserted nodes trivially inspectable.
const AdapterPackageDir = "heros_adapters"

// EmitAdapter renders one inserted adapter to a deterministic source file in the target's language. It
// dispatches on language (Go and Python today) and refuses an unknown one or an unknown catalog kind —
// both fail-closed, because a silently-skipped adapter would reintroduce the hidden-coercion problem the
// explicit-node design exists to prevent.
func EmitAdapter(a variantspec.InsertedAdapter, language string) (GeneratedFile, error) {
	switch strings.ToLower(strings.TrimSpace(language)) {
	case "go":
		return emitAdapterGo(a)
	case "python":
		return emitAdapterPython(a)
	default:
		return GeneratedFile{}, fmt.Errorf("%w: the adapter catalog emits Go or Python source; %q workflows cannot "+
			"receive a generated adapter yet", ErrLanguageNotRewritable, language)
	}
}

func emitAdapterGo(a variantspec.InsertedAdapter) (GeneratedFile, error) {
	body, err := emitBody(a)
	if err != nil {
		return GeneratedFile{}, err
	}
	fn := adapterFuncName(a)
	src := fmt.Sprintf(`// Code generated by heros typed-contracts adapter catalog (%s). DO NOT EDIT.
//
// Adapter %q bridges the data edge %s -> %s (catalog kind %q).
// It is an explicit, inspectable node carrying its own io_contract:
//   in:  %s
//   out: %s
// The transform validated in.satisfied-by(producer) and out.satisfies(consumer) before emitting this.
package %s

// %s is a pure transform of the upstream producer's output into the shape the downstream consumer
// requires. It applies only the declared %s operation, so it can neither drop a required field silently
// nor mutate its input.
func %s(in map[string]any) map[string]any {
%s
}
`,
		typedcontract.CatalogVersion,
		a.AdapterNodeID, a.FromNodeID, a.ToNodeID, a.CatalogKind,
		compactSchema(a.InSchema), compactSchema(a.OutSchema),
		AdapterPackageDir,
		fn, a.CatalogKind,
		fn, body,
	)
	formatted, err := format.Source([]byte(src))
	if err != nil {
		// A malformed emission is our bug, surfaced loudly rather than shipped as a broken diff.
		return GeneratedFile{}, fmt.Errorf("transform: emitted adapter %q does not format as Go: %w", a.AdapterNodeID, err)
	}
	return GeneratedFile{Path: AdapterPackageDir + "/" + adapterFileBase(a) + ".go", Content: formatted}, nil
}

// emitBody renders the kind-specific transform statements. Every branch copies through and mutates only
// the declared fields; the input map is never modified. Iteration is over sorted keys so the emitted
// bytes are deterministic.
func emitBody(a variantspec.InsertedAdapter) (string, error) {
	var b strings.Builder
	// The copy-through prologue: field-preserving kinds start from a full copy of the input so nothing
	// is dropped. Wrap/unwrap restructure the object and so return directly instead.
	prologue := "\tout := make(map[string]any, len(in))\n\tfor k, v := range in {\n\t\tout[k] = v\n\t}\n"
	switch typedcontract.CatalogKind(a.CatalogKind) {
	case typedcontract.KindRename:
		b.WriteString(prologue)
		for _, r := range sortedPairs(a.Params, "renames", "from", "to") {
			fmt.Fprintf(&b, "\tif v, ok := in[%q]; ok {\n\t\tout[%q] = v\n\t\tdelete(out, %q)\n\t}\n", r[0], r[1], r[0])
		}
		b.WriteString("\treturn out")
	case typedcontract.KindDefaultFill:
		b.WriteString(prologue)
		for _, f := range sortedFills(a.Params) {
			fmt.Fprintf(&b, "\tif _, ok := out[%q]; !ok {\n\t\tout[%q] = %s\n\t}\n", f.field, f.field, goLiteral(f.value))
		}
		b.WriteString("\treturn out")
	case typedcontract.KindCoerce:
		b.WriteString(prologue)
		for _, c := range sortedPairs(a.Params, "coercions", "field", "to") {
			// JSON numbers decode to float64 in Go, so an integer→number widening is the identity at
			// runtime; we still emit an explicit float64 assertion so the intent is legible in review.
			fmt.Fprintf(&b, "\tif v, ok := out[%q].(float64); ok {\n\t\tout[%q] = v // coerced to %s\n\t}\n", c[0], c[0], c[1])
		}
		b.WriteString("\treturn out")
	case typedcontract.KindWrap:
		key, _ := a.Params["key"].(string)
		if key == "" {
			return "", fmt.Errorf("transform: wrap adapter %q missing key param", a.AdapterNodeID)
		}
		fmt.Fprintf(&b, "\treturn map[string]any{%q: in}", key)
	case typedcontract.KindUnwrap:
		key, _ := a.Params["key"].(string)
		if key == "" {
			return "", fmt.Errorf("transform: unwrap adapter %q missing key param", a.AdapterNodeID)
		}
		fmt.Fprintf(&b, "\tif inner, ok := in[%q].(map[string]any); ok {\n\t\treturn inner\n\t}\n\treturn in", key)
	case typedcontract.KindProjection:
		b.WriteString(prologue)
		b.WriteString("\treturn out")
	default:
		return "", fmt.Errorf("transform: unknown adapter catalog kind %q for adapter %q", a.CatalogKind, a.AdapterNodeID)
	}
	return b.String(), nil
}

func adapterFuncName(a variantspec.InsertedAdapter) string {
	return "Adapter_" + sanitize(a.FromNodeID) + "_to_" + sanitize(a.ToNodeID) + "_" + a.CatalogKind
}

func adapterFileBase(a variantspec.InsertedAdapter) string {
	return "adapter_" + sanitize(a.FromNodeID) + "_" + sanitize(a.ToNodeID) + "_" + a.CatalogKind
}

func sanitize(s string) string {
	var b strings.Builder
	for _, r := range s {
		switch {
		case r >= 'a' && r <= 'z', r >= 'A' && r <= 'Z', r >= '0' && r <= '9':
			b.WriteRune(r)
		default:
			b.WriteRune('_')
		}
	}
	return b.String()
}

// sortedPairs pulls a list-of-objects param (e.g. renames:[{from,to}]) into a sorted [][2]string keyed
// on the first field, so emission order is stable regardless of the slice's construction order.
func sortedPairs(params map[string]any, listKey, a, b string) [][2]string {
	out := make([][2]string, 0)
	for _, m := range objectList(params[listKey]) {
		av, _ := m[a].(string)
		bv, _ := m[b].(string)
		out = append(out, [2]string{av, bv})
	}
	sort.Slice(out, func(i, j int) bool { return out[i][0] < out[j][0] })
	return out
}

type fillEntry struct {
	field string
	value any
}

func sortedFills(params map[string]any) []fillEntry {
	out := make([]fillEntry, 0)
	for _, m := range objectList(params["fills"]) {
		f, _ := m["field"].(string)
		out = append(out, fillEntry{field: f, value: m["value"]})
	}
	sort.Slice(out, func(i, j int) bool { return out[i].field < out[j].field })
	return out
}

// objectList normalises a param that is a list of objects, tolerating both the in-memory
// `[]map[string]any` (fresh from the catalog) and the `[]any` a JSON round-trip produces.
func objectList(v any) []map[string]any {
	switch t := v.(type) {
	case []map[string]any:
		return t
	case []any:
		out := make([]map[string]any, 0, len(t))
		for _, e := range t {
			if m, ok := e.(map[string]any); ok {
				out = append(out, m)
			}
		}
		return out
	default:
		return nil
	}
}

// goLiteral renders a JSON-decoded default value as a Go literal. Only the JSON scalar types can appear
// in a schema `default`; anything else is rendered via a conservative %#v.
func goLiteral(v any) string {
	switch t := v.(type) {
	case string:
		return fmt.Sprintf("%q", t)
	case bool:
		return fmt.Sprintf("%v", t)
	case float64:
		return fmt.Sprintf("%v", t)
	case nil:
		return "nil"
	default:
		return fmt.Sprintf("%#v", t)
	}
}

func compactSchema(s map[string]any) string {
	return typedcontract.MarshalCompact(s)
}

// AdapterPackagePython is where generated Python adapter sources live in the target tree.
const AdapterPackagePython = "heros_adapters"

// emitAdapterPython renders one inserted adapter as a deterministic Python module. The adapter is a pure
// function over a dict — the natural shape for a Python LLM workflow whose messages/response payloads are
// dicts — so it is the direct analogue of the Go emitter, and it makes the adapter catalog work for the
// large Python share of real agents (hermes-agent among them). Deterministic: sorted params, fixed
// formatting.
func emitAdapterPython(a variantspec.InsertedAdapter) (GeneratedFile, error) {
	body, err := emitBodyPython(a)
	if err != nil {
		return GeneratedFile{}, err
	}
	fn := pyFuncName(a)
	src := fmt.Sprintf(`# Code generated by heros typed-contracts adapter catalog (%s). DO NOT EDIT.
#
# Adapter %q bridges the data edge %s -> %s (catalog kind %q).
# It is an explicit, inspectable node carrying its own io_contract:
#   in:  %s
#   out: %s
# The transform validated in.satisfied-by(producer) and out.satisfies(consumer) before emitting this.


def %s(inp):
    """Pure transform of the producer's output into the shape the consumer requires.

    Applies only the declared %s operation; it neither drops a required field silently nor mutates its input.
    """
%s
`,
		typedcontract.CatalogVersion,
		a.AdapterNodeID, a.FromNodeID, a.ToNodeID, a.CatalogKind,
		compactSchema(a.InSchema), compactSchema(a.OutSchema),
		fn, a.CatalogKind, body,
	)
	path := AdapterPackagePython + "/" + adapterFileBase(a) + ".py"
	// Parse-check the emission (fail-loud): a malformed emitted adapter is our bug and must never ship
	// as a broken diff. discovery.ParseCheck runs the same tree-sitter parser Discovery uses for Python.
	if err := discovery.ParseCheck("python", path, []byte(src)); err != nil {
		return GeneratedFile{}, fmt.Errorf("transform: emitted Python adapter %q does not parse: %w", a.AdapterNodeID, err)
	}
	return GeneratedFile{Path: path, Content: []byte(src)}, nil
}

// emitBodyPython renders the kind-specific transform as indented Python statements (4-space indent, one
// level inside the function). It mirrors emitBody's semantics exactly.
func emitBodyPython(a variantspec.InsertedAdapter) (string, error) {
	var b strings.Builder
	prologue := "    out = dict(inp)\n"
	switch typedcontract.CatalogKind(a.CatalogKind) {
	case typedcontract.KindRename:
		b.WriteString(prologue)
		for _, r := range sortedPairs(a.Params, "renames", "from", "to") {
			fmt.Fprintf(&b, "    if %q in inp:\n        out[%q] = inp[%q]\n        del out[%q]\n", r[0], r[1], r[0], r[0])
		}
		b.WriteString("    return out")
	case typedcontract.KindDefaultFill:
		b.WriteString(prologue)
		for _, f := range sortedFills(a.Params) {
			fmt.Fprintf(&b, "    out.setdefault(%q, %s)\n", f.field, pyLiteral(f.value))
		}
		b.WriteString("    return out")
	case typedcontract.KindCoerce:
		b.WriteString(prologue)
		for _, c := range sortedPairs(a.Params, "coercions", "field", "to") {
			fmt.Fprintf(&b, "    if %q in out:\n        out[%q] = float(out[%q])  # coerced to %s\n", c[0], c[0], c[0], c[1])
		}
		b.WriteString("    return out")
	case typedcontract.KindWrap:
		key, _ := a.Params["key"].(string)
		if key == "" {
			return "", fmt.Errorf("transform: wrap adapter %q missing key param", a.AdapterNodeID)
		}
		fmt.Fprintf(&b, "    return {%q: inp}", key)
	case typedcontract.KindUnwrap:
		key, _ := a.Params["key"].(string)
		if key == "" {
			return "", fmt.Errorf("transform: unwrap adapter %q missing key param", a.AdapterNodeID)
		}
		fmt.Fprintf(&b, "    inner = inp.get(%q)\n    return inner if isinstance(inner, dict) else inp", key)
	case typedcontract.KindProjection:
		b.WriteString(prologue)
		b.WriteString("    return out")
	default:
		return "", fmt.Errorf("transform: unknown adapter catalog kind %q for adapter %q", a.CatalogKind, a.AdapterNodeID)
	}
	return b.String(), nil
}

func pyFuncName(a variantspec.InsertedAdapter) string {
	return "adapter_" + sanitize(a.FromNodeID) + "_to_" + sanitize(a.ToNodeID) + "_" + a.CatalogKind
}

// pyLiteral renders a JSON-decoded default value as a Python literal.
func pyLiteral(v any) string {
	switch t := v.(type) {
	case string:
		return fmt.Sprintf("%q", t)
	case bool:
		if t {
			return "True"
		}
		return "False"
	case float64:
		return fmt.Sprintf("%v", t)
	case nil:
		return "None"
	default:
		return fmt.Sprintf("%#v", t)
	}
}
