package transform

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// The generated GO memory module (P18 §4).
//
// # Why Go's module is generic and Python's is not
//
// Python's module reads message CONTENT — it is a dict, so `m["content"]` works for any SDK. Go's cannot:
// a message is the customer's SDK type, and reading a field off it would mean importing the SDK into
// generated code (a dependency they did not choose) or reflecting over a shape this engine has no
// evidence for.
//
// So the Go module is CONTENT-BLIND by construction: `Recall[T any](nodeID string, msgs []T) []T` moves
// values without inspecting them. That is enough for the strategies whose retention is a function of
// COUNT, and it is not enough for the ones whose retention is a function of content — which is why
// `memoryContentBlindStrategies` exists and why Go materializes a strict subset of what Python does.
//
// 🔴 That subset is a per-(language, strategy) coverage fact, stated in the table rather than discovered
// at apply time. A Go user selecting `summary-buffer` is refused with the reason, not handed a
// `scratchpad` wearing its name.

// goMemoryModuleDir is the package directory the generated Go module lands in.
const goMemoryModuleDir = "agentmem"

var (
	goMemoryModulePath = filepath.Join(goMemoryModuleDir, "agentmem.go")
	goMemoryDocPath    = filepath.Join(goMemoryModuleDir, "agentmem.json")
)

// goModulePath reads the target's own module path out of its go.mod, so the generated import is the one
// that actually resolves in the customer's tree.
//
// 🚫 It is READ, never assumed. A guessed import path produces a diff that does not compile — the exact
// failure ADR-001 names — and unlike a wrong value it fails for a reason a reader cannot act on ("why is
// it importing something that isn't mine?").
func goModulePath(root string) (string, error) {
	raw, err := os.ReadFile(filepath.Join(root, "go.mod"))
	if err != nil {
		return "", fmt.Errorf("transform: reading the target's go.mod to derive the memory import path: %w", err)
	}
	for _, line := range strings.Split(string(raw), "\n") {
		if rest, ok := strings.CutPrefix(strings.TrimSpace(line), "module "); ok {
			if p := strings.TrimSpace(rest); p != "" {
				return p, nil
			}
		}
	}
	return "", fmt.Errorf("transform: the target's go.mod declares no module path, so the generated memory " +
		"module has no import path that would resolve")
}

// goMemoryModule is the emitted Go module.
//
// 🔴 A CONSTANT, like the Python one: nothing about a node, a strategy, or a parameter is interpolated,
// so regeneration is byte-identical and a parameter change never appears in the code diff. Its imports
// are `encoding/json`, `os`, `path/filepath`, `sort`, `strings` and `sync` — standard library only. It
// makes no provider call and reads no credential.
//
// 🚫 It implements only the CONTENT-BLIND strategies. A content-reading strategy reaching it is a bug in
// the materializer's gating, so it returns an error rather than silently degrading to `scratchpad` — a
// degradation would run one strategy under another's config_hash, which is the failure the whole axis
// exists to prevent.
const goMemoryModule = `// Package agentmem is the generated memory runtime for the call sites heros rewrote.
// DO NOT EDIT. Regenerated byte-identically from the same configuration.
//
// It reads its configuration from agentmem.json, which is data: retuning a parameter is a change to that
// file, not to this one. It is dependency-free (standard library only) and makes no network or provider
// call.
//
// It is deliberately CONTENT-BLIND. A message here is your SDK's own type, so this package moves values
// without inspecting them — which is why it implements the strategies whose retention is a function of
// count, and refuses the ones that need to read message text. Those are refused at codemod time, so
// reaching the error below means the generator gated something wrong.
//
// Sessions
//
// Memory is scoped by (node, session). This package will not invent a session id: a defaulted one merges
// conversations that must stay separate, which is a cross-user leak in a server process. Supply one with
// the HEROS_MEMORY_SESSION environment variable or agentmem.SetSession.
package agentmem

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"runtime"
	"sync"
)

// ErrNoSession is returned when no session id is available to scope memory.
var ErrNoSession = fmt.Errorf("agentmem: no memory session id: set HEROS_MEMORY_SESSION or call " +
	"agentmem.SetSession. This package refuses to default one because a defaulted session merges " +
	"conversations that must stay separate")

type config struct {
	Nodes map[string]struct {
		Strategy string ` + "`json:\"strategy\"`" + `
		Params   struct {
			MaxEntries int ` + "`json:\"max_entries\"`" + `
		} ` + "`json:\"params\"`" + `
	} ` + "`json:\"nodes\"`" + `
}

var (
	mu      sync.Mutex
	entries = map[string][]any{}
	session string
	cfg     *config
)

// SetSession scopes subsequent Recall/Record calls to this conversation.
func SetSession(id string) {
	mu.Lock()
	defer mu.Unlock()
	session = id
}

func currentSession() (string, error) {
	mu.Lock()
	s := session
	mu.Unlock()
	if s == "" {
		s = os.Getenv("HEROS_MEMORY_SESSION")
	}
	if s == "" {
		return "", ErrNoSession
	}
	return s, nil
}

func load() (*config, error) {
	mu.Lock()
	defer mu.Unlock()
	if cfg != nil {
		return cfg, nil
	}
	_, self, _, ok := runtime.Caller(0)
	if !ok {
		return nil, fmt.Errorf("agentmem: cannot locate its own configuration")
	}
	raw, err := os.ReadFile(filepath.Join(filepath.Dir(self), "agentmem.json"))
	if err != nil {
		return nil, fmt.Errorf("agentmem: reading agentmem.json: %w", err)
	}
	var c config
	if err := json.Unmarshal(raw, &c); err != nil {
		return nil, fmt.Errorf("agentmem: parsing agentmem.json: %w", err)
	}
	cfg = &c
	return cfg, nil
}

func settings(nodeID string) (string, int, string, error) {
	c, err := load()
	if err != nil {
		return "", 0, "", err
	}
	node, ok := c.Nodes[nodeID]
	if !ok {
		return "", 0, "", fmt.Errorf("agentmem: no memory configuration for node %s", nodeID)
	}
	s, err := currentSession()
	if err != nil {
		return "", 0, "", err
	}
	return node.Strategy, node.Params.MaxEntries, nodeID + "\x00" + s, nil
}

// Recall returns the message list to send: what memory holds for this node and session, then the turns
// you wrote. Your own turns are always preserved, in order, at the end.
func Recall[T any](nodeID string, msgs []T) []T {
	out, err := recall(nodeID, msgs)
	if err != nil {
		panic(err)
	}
	return out
}

func recall[T any](nodeID string, msgs []T) ([]T, error) {
	strategy, limit, key, err := settings(nodeID)
	if err != nil {
		return nil, err
	}
	if strategy == "none" {
		return msgs, nil
	}
	if strategy != "scratchpad" {
		return nil, fmt.Errorf("agentmem: strategy %q needs to read message content, which this package "+
			"cannot do for your SDK's message type; it should have been refused at codemod time", strategy)
	}
	if limit < 1 {
		return nil, fmt.Errorf("agentmem: scratchpad needs max_entries >= 1")
	}

	mu.Lock()
	kept := entries[key]
	if len(kept) > limit {
		kept = kept[len(kept)-limit:]
	}
	held := make([]any, len(kept))
	copy(held, kept)
	mu.Unlock()

	out := make([]T, 0, len(held)+len(msgs))
	for _, e := range held {
		if v, ok := e.(T); ok {
			out = append(out, v)
		}
	}
	return append(out, msgs...), nil
}

// Record stores a completed turn: what you sent, and what came back.
func Record[T any](nodeID string, sent []T, reply T) {
	if err := record(nodeID, sent, reply); err != nil {
		panic(err)
	}
}

func record[T any](nodeID string, sent []T, reply T) error {
	strategy, limit, key, err := settings(nodeID)
	if err != nil {
		return err
	}
	if strategy == "none" {
		return nil
	}
	if strategy != "scratchpad" {
		return fmt.Errorf("agentmem: strategy %q needs to read message content, which this package cannot "+
			"do for your SDK's message type; it should have been refused at codemod time", strategy)
	}
	if limit < 1 {
		return fmt.Errorf("agentmem: scratchpad needs max_entries >= 1")
	}

	mu.Lock()
	defer mu.Unlock()
	for _, m := range sent {
		entries[key] = append(entries[key], any(m))
	}
	entries[key] = append(entries[key], any(reply))
	if len(entries[key]) > limit {
		entries[key] = append([]any(nil), entries[key][len(entries[key])-limit:]...)
	}
	return nil
}
`
