#!/usr/bin/env bash
# One-command deploy of the platform on a single Ubuntu VM (P19 open-core form).
#
# The closest thing to a "one button" for a seven-service stateful stack: on a FRESH Ubuntu 24.04 box
# it installs Docker, BUILDS the platform's own images on the box (no registry), GENERATES every secret
# once, brings the whole Compose stack up under one aggregated /readyz, and stands up Caddy for
# automatic HTTPS on your domain. Re-running is idempotent — the same command upgrades (rebuild +
# `up -d` converges) and never re-prompts or regenerates a secret that already exists.
#
# Usage (from the repo root, as root or with sudo):
#   sudo bash deploy/scripts/bootstrap-vm.sh <domain>
#
# Example:
#   sudo bash deploy/scripts/bootstrap-vm.sh heros-agent.space
#
# Two prerequisites a script cannot do for you:
#   1) A VM with a public IP (DigitalOcean 4vCPU/8GB droplet recommended).
#   2) A DNS A record for <domain> pointing at that IP — Caddy cannot get a certificate until it does.
#
# Scope: this stands up the platform + the CUSTOMER console (the product surface). The OPERATOR console
# is an internal surface that requires a real SSO/MFA identity provider in production, so it is added
# separately (docker-compose.admin-console.yml with ADMIN_IDENTITY_MODE=configured), not by this button.
set -euo pipefail

DOMAIN="${1:?usage: bootstrap-vm.sh <domain>   (e.g. heros-agent.space)}"

REPO_ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
cd "$REPO_ROOT"
ENV_IMAGES="deploy/.env.deploy-images"
ENV_PLATFORM="deploy/.env.platform"
STATE_DIR="/var/lib/heros-deploy"
mkdir -p "$STATE_DIR" deploy/caddy

log() { printf '\n\033[1;36m▸ %s\033[0m\n' "$*"; }
gen()  { openssl rand -hex 24; }

# ── 1. Docker ───────────────────────────────────────────────────────────────────────────────────
if ! command -v docker >/dev/null 2>&1; then
  log "Installing Docker Engine + Compose plugin"
  curl -fsSL https://get.docker.com | sh
else
  log "Docker already present ($(docker --version))"
fi
docker compose version >/dev/null 2>&1 || { echo "docker compose plugin missing" >&2; exit 1; }

# ── 2. Image references (platform images build locally; store images pull by public tag) ─────────
# Kept separate from deploy/images.env (the release pipeline's digest-pinned contract) so this deploy
# path works today with images that actually exist.
if [ ! -f "$ENV_IMAGES" ]; then
  log "Writing $ENV_IMAGES (platform images build locally; stores by public tag)"
  cat > "$ENV_IMAGES" <<EOF
AGENTD_IMAGE=heros-agentd:local
CONSOLE_IMAGE=heros-console:local
POSTGRES_IMAGE=postgres:16.4-alpine
OBJECT_STORE_IMAGE=minio/minio:RELEASE.2024-09-13T20-26-02Z
QUEUE_IMAGE=nats:2.10-alpine
VECTOR_STORE_IMAGE=qdrant/qdrant:v1.11.3
GRAPH_STORE_IMAGE=neo4j:5-community
EOF
fi

# ── 3. Secrets — generated ONCE, kept across re-runs (idempotent; never re-prompts) ──────────────
if [ ! -f "$ENV_PLATFORM" ]; then
  log "Generating platform secrets into $ENV_PLATFORM (once — kept on every re-run)"
  SIGNIN_ASSERTION="$(gen)"
  cat > "$ENV_PLATFORM" <<EOF
# GENERATED by bootstrap-vm.sh on first run. Contains live secrets — chmod 600, never commit.
AGENTD_PORT=4321
CONSOLE_PORT=4320
HEROS_SECRETS_SOURCE=env
OPENAI_API_KEY=${OPENAI_API_KEY:-}
ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY:-}
POSTGRES_DB=heros
POSTGRES_USER=heros
POSTGRES_PASSWORD=$(gen)
POSTGRES_BACKUP_CRON=17 3 * * *
POSTGRES_BACKUP_RETENTION_DAYS=14
OBJECT_STORE_ROOT_USER=heros
OBJECT_STORE_ROOT_PASSWORD=$(gen)
NEO4J_AUTH=neo4j/$(gen)
CONSOLE_PLATFORM_CREDENTIAL=$(gen)
CONSOLE_TENANT_IDENTITY=configured
CONSOLE_TENANT_ASSERTIONS={"${SIGNIN_ASSERTION}":"default"}
CONSOLE_SESSION_TTL_SECONDS=28800
CONSOLE_UPSTREAM_TIMEOUT_MS=10000
EOF
  chmod 600 "$ENV_PLATFORM"
  echo "$SIGNIN_ASSERTION" > "$STATE_DIR/console-signin-assertion.txt"
else
  log "Reusing existing secrets in $ENV_PLATFORM (already present)"
fi

# ── 4. Caddyfile (HTTPS for the domain) ──────────────────────────────────────────────────────────
log "Writing deploy/caddy/Caddyfile for $DOMAIN"
cat > deploy/caddy/Caddyfile <<EOF
$DOMAIN {
    reverse_proxy console:4320
}
EOF

# ── 5. Build + up (idempotent: converges; upgrade = re-run) ──────────────────────────────────────
ENVFILES=(--env-file "$ENV_IMAGES" --env-file "$ENV_PLATFORM")
FILES=(-f deploy/docker-compose.platform.yml
       -f deploy/docker-compose.platform.build.yml
       -f deploy/docker-compose.caddy.yml)
log "Building images on this box and starting the stack (a few minutes on first run)"
docker compose "${ENVFILES[@]}" "${FILES[@]}" up -d --build --remove-orphans

# ── 6. Wait for the aggregated /readyz to go green ───────────────────────────────────────────────
AGENTD_PORT="$(grep '^AGENTD_PORT=' "$ENV_PLATFORM" | cut -d= -f2)"
log "Waiting for the platform to report ready (aggregated /readyz on :$AGENTD_PORT)…"
for i in $(seq 1 60); do
  body="$(curl -fsS "http://127.0.0.1:${AGENTD_PORT}/readyz" 2>/dev/null || true)"
  case "$body" in
    *'"status":"ready"'*) log "READY — every component reports healthy."; break ;;
  esac
  if [ "$i" = 60 ]; then
    echo "readiness did not go green in time. Diagnose with: bash deploy/scripts/doctor.sh" >&2
    echo "last /readyz: ${body:-<no response>}" >&2
  fi
  sleep 5
done

# ── 7. Print how to reach it ─────────────────────────────────────────────────────────────────────
log "Done."
echo "  Customer console:  https://$DOMAIN"
echo "  Sign-in tenant credential:  $(cat "$STATE_DIR/console-signin-assertion.txt" 2>/dev/null || echo "see CONSOLE_TENANT_ASSERTIONS in $ENV_PLATFORM")"
echo
echo "  Status:  docker compose ${ENVFILES[*]} ${FILES[*]} ps"
echo "  Health:  curl -fsS http://127.0.0.1:${AGENTD_PORT}/readyz   (aggregated, names any degraded component)"
echo "  Operate: bash deploy/scripts/doctor.sh   ·   backups run daily to the postgres-backups volume"
echo "  Upgrade: git pull && sudo bash deploy/scripts/bootstrap-vm.sh $DOMAIN   (same command; state preserved)"
echo
echo "  Model calls (eval/diagnosis): set OPENAI_API_KEY / ANTHROPIC_API_KEY in $ENV_PLATFORM and re-run,"
echo "  or leave blank — discovery/apply/run work without them; only model-dependent stages report degraded."
