#!/usr/bin/env bash
# One-command deploy of the platform on a single Ubuntu VM (P19 open-core form).
#
# The closest thing to a "one button" for a seven-service stateful stack: on a FRESH Ubuntu 24.04 box
# it installs Docker, BUILDS the platform's own images on the box (no registry), GENERATES every secret
# once, brings the whole Compose stack up under one aggregated /readyz, and stands up Caddy for
# automatic HTTPS on your domain. Re-running is idempotent — the same command upgrades (rebuild +
# `up -d` converges) and never re-prompts or regenerates a secret that already exists.
#
# Usage (from the repo root, as root or with sudo):
#   sudo bash deploy/scripts/bootstrap-vm.sh <domain>
#
# Example:
#   sudo bash deploy/scripts/bootstrap-vm.sh heros-agent.space
#
# Two prerequisites a script cannot do for you:
#   1) A VM with a public IP (DigitalOcean 4vCPU/8GB droplet recommended).
#   2) A DNS A record for <domain> pointing at that IP — Caddy cannot get a certificate until it does.
#
# Scope: this stands up the platform + the CUSTOMER console (the product surface). The OPERATOR console
# is an internal surface that requires a real SSO/MFA identity provider in production, so it is added
# separately (docker-compose.admin-console.yml with ADMIN_IDENTITY_MODE=configured), not by this button.
set -euo pipefail

DOMAIN="${1:?usage: bootstrap-vm.sh <domain>   (e.g. heros-agent.space)}"

REPO_ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
cd "$REPO_ROOT"
ENV_IMAGES="deploy/.env.deploy-images"
ENV_PLATFORM="deploy/.env.platform"
STATE_DIR="/var/lib/heros-deploy"
mkdir -p "$STATE_DIR" deploy/caddy

log() { printf '\n\033[1;36m▸ %s\033[0m\n' "$*"; }
gen()  { openssl rand -hex 24; }

# ensure_env_key NAME VALUE — append NAME=VALUE to $ENV_PLATFORM when NAME is ABSENT from it. Never
# overwrites a value that is already there.
#
# 🔴 This exists because of a specific trap in this script's own idempotency. Section 3 writes the whole
# env file ONLY when it does not exist, so on an already-deployed box every variable added to that
# heredoc later is written to a file nobody re-reads: the deploy "succeeds", the operator sees the new
# feature documented, and the running container never receives the variable. That failure mode is silent
# on both ends — the script prints nothing missing and the platform reports the capability absent for a
# reason ("no mode declared") that is true and completely unhelpful.
#
# Appending only when absent keeps both properties that matter: a first run gets the value, and a re-run
# never rotates a credential under a live deployment.
ensure_env_key() {
  local name="$1" value="$2"
  [ -n "$value" ] || return 0
  if grep -q "^${name}=" "$ENV_PLATFORM" 2>/dev/null; then
    return 0
  fi
  printf '%s=%s\n' "$name" "$value" >> "$ENV_PLATFORM"
  log "Added $name to $ENV_PLATFORM (it was absent)"
}

# ── 1. Docker ───────────────────────────────────────────────────────────────────────────────────
if ! command -v docker >/dev/null 2>&1; then
  log "Installing Docker Engine + Compose plugin"
  curl -fsSL https://get.docker.com | sh
else
  log "Docker already present ($(docker --version))"
fi
docker compose version >/dev/null 2>&1 || { echo "docker compose plugin missing" >&2; exit 1; }

# ── 2. Image references (platform images build locally; store images pull by public tag) ─────────
# Kept separate from deploy/images.env (the release pipeline's digest-pinned contract) so this deploy
# path works today with images that actually exist.
if [ ! -f "$ENV_IMAGES" ]; then
  log "Writing $ENV_IMAGES (platform images build locally; stores by public tag)"
  cat > "$ENV_IMAGES" <<EOF
AGENTD_IMAGE=heros-agentd:local
CONSOLE_IMAGE=heros-console:local
POSTGRES_IMAGE=postgres:16.4-alpine
OBJECT_STORE_IMAGE=minio/minio:RELEASE.2024-09-13T20-26-02Z
QUEUE_IMAGE=nats:2.10-alpine
VECTOR_STORE_IMAGE=qdrant/qdrant:v1.11.3
GRAPH_STORE_IMAGE=neo4j:5-community
EOF
fi

# ── 3. Secrets — generated ONCE, kept across re-runs (idempotent; never re-prompts) ──────────────
if [ ! -f "$ENV_PLATFORM" ]; then
  log "Generating platform secrets into $ENV_PLATFORM (once — kept on every re-run)"
  SIGNIN_ASSERTION="$(gen)"
  cat > "$ENV_PLATFORM" <<EOF
# GENERATED by bootstrap-vm.sh on first run. Contains live secrets — chmod 600, never commit.
AGENTD_PORT=4321
CONSOLE_PORT=4320
HEROS_SECRETS_SOURCE=env
OPENAI_API_KEY=${OPENAI_API_KEY:-}
ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY:-}
POSTGRES_DB=heros
POSTGRES_USER=heros
POSTGRES_PASSWORD=$(gen)
POSTGRES_BACKUP_CRON=17 3 * * *
POSTGRES_BACKUP_RETENTION_DAYS=14
OBJECT_STORE_ROOT_USER=heros
OBJECT_STORE_ROOT_PASSWORD=$(gen)
NEO4J_AUTH=neo4j/$(gen)
CONSOLE_PLATFORM_CREDENTIAL=$(gen)
CONSOLE_TENANT_IDENTITY=configured
CONSOLE_TENANT_ASSERTIONS={"${SIGNIN_ASSERTION}":"default"}
CONSOLE_SESSION_TTL_SECONDS=28800
CONSOLE_UPSTREAM_TIMEOUT_MS=10000
EOF
  chmod 600 "$ENV_PLATFORM"
  echo "$SIGNIN_ASSERTION" > "$STATE_DIR/console-signin-assertion.txt"
else
  log "Reusing existing secrets in $ENV_PLATFORM (already present)"
fi

# ── 3b. P21 COLLECTION — taking money, declared rather than inferred ─────────────────────────────
#
# Three variables, supplied from the invoking environment and then persisted, so the SECOND run of this
# script does not need them again:
#
#   BILLING_MODE=test|live          its PRESENCE is what mounts checkout, plan changes and the webhook
#   BILLING_PROVIDER_API_KEY        the processor's server-side key
#   BILLING_WEBHOOK_SECRET          the signing secret inbound webhooks are verified against
#
# ⚠️ `live` MOVES REAL MONEY. Nothing here infers it — not from the key's prefix, not from the hostname.
# The platform refuses a live key under a test mode and a test key under a live one (ErrStripeKeyMode),
# so a mismatch is a refusal at the first call rather than a customer charged from the wrong account.
#
# Unset ⇒ collection is not mounted at all, which is the correct state for every open-core install: the
# platform still bills (P7 reads what a customer owes); it just cannot COLLECT.
#
# 🔴 A live mode with no plan catalog is a checkout button over an empty price list. The catalog is a
# FILE the operator publishes at deploy/config/plans.json (git-ignored — it carries prices), mounted
# read-only into the container at /etc/heros/plans.json. Checked here rather than discovered by the
# first customer to click Upgrade.
if [ -n "${BILLING_MODE:-}" ]; then
  case "$BILLING_MODE" in
    test|live) : ;;
    *) echo "BILLING_MODE must be 'test' or 'live' (got '$BILLING_MODE') — a typo defaulted to test is a checkout button that takes no money" >&2; exit 1 ;;
  esac
  ensure_env_key BILLING_MODE "$BILLING_MODE"
  ensure_env_key BILLING_PROVIDER_API_KEY "${BILLING_PROVIDER_API_KEY:-}"
  ensure_env_key BILLING_WEBHOOK_SECRET "${BILLING_WEBHOOK_SECRET:-}"
  if [ ! -f deploy/config/plans.json ]; then
    echo "BILLING_MODE=$BILLING_MODE was declared but deploy/config/plans.json does not exist." >&2
    echo "Publish the plan catalog first — without it billing cannot resolve which plan a customer is on," >&2
    echo "and neither the billing page nor checkout is mounted. See deploy/config/README.md." >&2
    exit 1
  fi
fi

# ── 4. Caddyfile (HTTPS for the domain) ──────────────────────────────────────────────────────────
#
# 🔴 TWO handles, and the first one is the whole reason collection can work at all. Every path but one
# goes to the customer console; `/billing/webhook` goes to the PLATFORM API, because that is the single
# route on this platform that accepts unsolicited internet traffic (internal/api/p21.go). Proxying
# everything to the console — which is what this file did until now — leaves the processor's webhook
# answering 404 forever: checkout completes, the customer is charged, and the platform never learns the
# subscription became active. Nothing about that failure is visible from either console.
#
# ⚠️ Never a prefix. `/billing/*`, `/api/v1/*` or a bare `reverse_proxy agentd:4321` would put the whole
# platform API — every tenant-scoped route behind it — on the public internet. Caddy's `path` matcher is
# EXACT unless a path ends in `*`, so the list below is the Compose equivalent of `pathType: Exact`.
#
# ── 🔴 P29 · THE SUBSTRATE-PARITY DEFECT, and it was larger than the one that prompted the look ──────
#
# This file used to publish exactly ONE agentd path: `/billing/webhook`. Everything else went to the
# console. So on a Compose deployment — the single-VM install this script exists to produce —
# `heros login` reached Next.js and got a 404, and so did `heros link`, and so did the device
# authorization pair, and so did password sign-in. The CLI could not authenticate AT ALL against a box
# installed by our own bootstrap script.
#
# The Kubernetes overlay had six of those rules and a fence checking them. This substrate had one rule
# and no fence, and nothing in the repository compared the two — which is the same shape as the original
# defect (a route's reachability living in a deployment file and its existence living in Go) with one
# more axis: reachability now differs by SUBSTRATE, and only one substrate was being checked.
#
# So the list below is the single source, and `internal/api/ingress_fence_test.go` reads it FROM THIS
# FILE and requires it to equal `api.PublicRoutes()` — the same list it requires the k8s overlay to
# carry. Adding a public route now fails a test twice, once per substrate, rather than working in
# production and 404ing on every self-hosted install.
# 🔴 The LONG-LIVED paths, listed separately because they need a different proxy setting, not a
# different exposure. Every entry here must also appear in PLATFORM_PUBLIC_PATHS below — the stream is
# published like any other public route; what differs is only that its response must not be buffered.
# `TestEveryStreamPathIsPublishedAndUnbuffered` asserts both directions.
PLATFORM_STREAM_PATHS="/api/v1/conversation-stream"

PLATFORM_PUBLIC_PATHS="/api/v1/whoami /api/v1/run-links /billing/webhook /api/v1/device/authorize /api/v1/device/token /api/v1/auth/password/signin /api/v1/workflow-ir /api/v1/workflow-source /api/v1/workflow-source-discovery /api/v1/proposal-verdicts /api/v1/transform-receipts /api/v1/proposal-generations /api/v1/agent-definition /api/v1/repo-connections /api/v1/repo-connection-revocations /api/v1/repo-connection-reads /api/v1/assessments /api/v1/improvement-plans /api/v1/improvement-runs /api/v1/improvement-decisions /api/v1/local-pairing-claims /api/v1/conversations /api/v1/conversation-turns /api/v1/conversation-stream /api/v1/conversation-approvals /api/v1/conversation-trace"

# ── 🔴 P32 · OUTBOUND: THE PLATFORM CLONES CUSTOMER REPOSITORIES ─────────────────────────────────
#
# This box makes OUTBOUND HTTPS connections to code hosts. That is a new egress class as of P32, it is
# not implicitly permitted because it is git, and an operator who firewalls outbound traffic has to
# know about it or repository connections fail with `network` and nothing says why.
#
#   github.com   gitlab.com   bitbucket.org
#
# These are the complete set, they come from `sourceingest.CloneHosts()`, and
# `TestForgeHostsAreOnTheEgressAllowlist` checks this list against that function — so a fourth forge
# added in Go makes this script go red rather than silently widening what the box pulls.
#
# ⚠️ A deployment that does NOT want the platform reaching code hosts simply does not create any
# repository connection: the routes stay mounted, no grant exists, and every workflow reads through a
# pushed bundle exactly as before. No feature is gated on a connection.
PLATFORM_CLONE_HOSTS="github.com gitlab.com bitbucket.org"

# ── 🔴 P31 · THE STREAM MUST NOT BE BUFFERED, and a buffering hop fails SILENTLY ─────────────────
#
# `/api/v1/conversation-stream` is Server-Sent Events. A reverse proxy that buffers turns streaming into
# BATCHING: the stream still completes, nothing errors, every message arrives at the end in one burst,
# and the failure is indistinguishable from slowness at the application layer. There is no status code
# for it and no log line — the only symptom is a conversation that sits blank for four minutes and then
# fills instantly, which reads as a slow platform rather than as a broken proxy.
#
# Caddy's `flush_interval -1` disables response buffering for a handler. It is set on a handler of its
# OWN — narrower than the platform handle above — so the setting cannot be widened by accident to routes
# that benefit from buffering, and so a reader can see which route depends on it.
#
# ⚠️ Caddy's path matcher is exact-unless-starred, and this route carries a query string rather than a
# path parameter, so the bare path is the whole match.
#
# `make console-edge-proof` asserts INCREMENTAL ARRIVAL through the running edge, because this setting
# is a request to one hop and the assertion is a fact about all of them.
log "Writing deploy/caddy/Caddyfile for $DOMAIN"
cat > deploy/caddy/Caddyfile <<EOF
$DOMAIN {
    @stream path $PLATFORM_STREAM_PATHS
    handle @stream {
        reverse_proxy agentd:4321 {
            flush_interval -1
        }
    }
    @platform path $PLATFORM_PUBLIC_PATHS
    handle @platform {
        reverse_proxy agentd:4321
    }
    handle {
        reverse_proxy console:4320
    }
}
EOF

# ── 5. Build + up (idempotent: converges; upgrade = re-run) ──────────────────────────────────────
ENVFILES=(--env-file "$ENV_IMAGES" --env-file "$ENV_PLATFORM")
FILES=(-f deploy/docker-compose.platform.yml
       -f deploy/docker-compose.platform.build.yml
       -f deploy/docker-compose.caddy.yml)
log "Building images on this box and starting the stack (a few minutes on first run)"
docker compose "${ENVFILES[@]}" "${FILES[@]}" up -d --build --remove-orphans

# ── 6. Wait for the aggregated /readyz to go green ───────────────────────────────────────────────
AGENTD_PORT="$(grep '^AGENTD_PORT=' "$ENV_PLATFORM" | cut -d= -f2)"
log "Waiting for the platform to report ready (aggregated /readyz on :$AGENTD_PORT)…"
for i in $(seq 1 60); do
  body="$(curl -fsS "http://127.0.0.1:${AGENTD_PORT}/readyz" 2>/dev/null || true)"
  case "$body" in
    *'"status":"ready"'*) log "READY — every component reports healthy."; break ;;
  esac
  if [ "$i" = 60 ]; then
    echo "readiness did not go green in time. Diagnose with: bash deploy/scripts/doctor.sh" >&2
    echo "last /readyz: ${body:-<no response>}" >&2
  fi
  sleep 5
done

# ── 7. Print how to reach it ─────────────────────────────────────────────────────────────────────
log "Done."
echo "  Customer console:  https://$DOMAIN"
echo "  Sign-in tenant credential:  $(cat "$STATE_DIR/console-signin-assertion.txt" 2>/dev/null || echo "see CONSOLE_TENANT_ASSERTIONS in $ENV_PLATFORM")"
echo
echo "  Status:  docker compose ${ENVFILES[*]} ${FILES[*]} ps"
echo "  Health:  curl -fsS http://127.0.0.1:${AGENTD_PORT}/readyz   (aggregated, names any degraded component)"
echo "  Operate: bash deploy/scripts/doctor.sh   ·   backups run daily to the postgres-backups volume"
echo "  Upgrade: git pull && sudo bash deploy/scripts/bootstrap-vm.sh $DOMAIN   (same command; state preserved)"
echo
echo "  Model calls (eval/diagnosis): set OPENAI_API_KEY / ANTHROPIC_API_KEY in $ENV_PLATFORM and re-run,"
echo "  or leave blank — discovery/apply/run work without them; only model-dependent stages report degraded."
