// Command docsfacts emits the machine-readable facts P23's documentation is generated from and fenced
// against.
//
// # Why a Go program writing JSON, rather than the console's scripts reading Go
//
// The same shape ADR-007 already uses for console types, for the same reason: the facts live in Go, the
// consumers are Node scripts, and a JavaScript parser for Go source is a second implementation of the
// truth that drifts silently.
//
//	make docs-facts         regenerate
//	make docs-facts-check   regenerate into a temp file and diff — the drift gate
//
// The artifact is CHECKED IN. A `.gitignore`d build product cannot be diffed in review, and the diff is
// where "somebody added a subcommand" becomes visible to the person who has to document it. It also means
// the console builds with no Go toolchain — which the console container does not have.
//
// # What it emits, and who reads each part
//
//	commands, flags, exit codes  gen-cli-reference.mjs writes the reference; scan-cli fences it both ways
//	metrics                      scan-metric checks a documented metric's name, unit and computation
//	channels, claims             gen-install-content.mjs and scan-install; the honesty gate for install docs
//	schemas                      gen-schema-reference.mjs
//	version                      every page's `platform_version`, so no page hand-types it
//
// # What it deliberately does not emit
//
// Anything about the HTTP API. There is no OpenAPI document in this repository (verified), the API
// reference tier therefore ships ABSENT with its reason, and `scan-api` REFUSES any documented endpoint
// rather than passing vacuously (decisions/p23-one-way-doors.md §1.5). Emitting a hand-assembled route
// list here would be exactly the fiction that decision forbids.
package main

import (
	"encoding/json"
	"fmt"
	"os"
	"sort"

	"github.com/heros-foreal/agentd/internal/cli"
	"github.com/heros-foreal/agentd/internal/distribution"
	"github.com/heros-foreal/agentd/internal/telemetry"
)

type flagFact struct {
	Name    string `json:"name"`
	Type    string `json:"type"`
	Default string `json:"default"`
	Env     string `json:"env"`
	Summary string `json:"summary"`
}

type commandFact struct {
	Name         string     `json:"name"`
	Summary      string     `json:"summary"`
	Availability string     `json:"availability"`
	Offline      bool       `json:"offline"`
	NeedsAccount bool       `json:"needs_account"`
	Flags        []flagFact `json:"flags"`
	Example      string     `json:"example"`
	Success      string     `json:"success"`
	SuccessExit  int        `json:"success_exit"`
	Unavailable  string     `json:"unavailable,omitempty"`
}

type channelFact struct {
	ID           string   `json:"id"`
	Label        string   `json:"label"`
	GOOSes       []string `json:"goos"`
	Publication  string   `json:"publication"`
	Delivered    bool     `json:"delivered"`
	Blocker      string   `json:"blocker,omitempty"`
	ManagerOwned bool     `json:"manager_owned"`
	Verification string   `json:"verification"`
	Install      string   `json:"install"`
	Upgrade      string   `json:"upgrade"`
	Uninstall    string   `json:"uninstall"`
	Pin          string   `json:"pin"`
}

type facts struct {
	Schema          string                       `json:"schema"`
	Note            string                       `json:"note"`
	ToolVersion     string                       `json:"tool_version"`
	ContractVersion string                       `json:"contract_version"`
	EnvPrefix       string                       `json:"env_prefix"`
	ProjectFile     string                       `json:"project_file"`
	Precedence      []string                     `json:"config_precedence"`
	Commands        []commandFact                `json:"commands"`
	ExitCodes       []cli.ExitCode               `json:"exit_codes"`
	Metrics         []telemetry.MetricDefinition `json:"metrics"`
	Channels        []channelFact                `json:"channels"`
	// TrustClaims is the inventoried vocabulary a document may only use when the release earned it. The
	// install fence refuses a page that claims one this release did not deliver.
	TrustClaims []string `json:"trust_claims"`
	// APIReference records the ABSENT tier and its reason, in the artifact rather than only in prose, so
	// `scan-api` can refuse a documented endpoint by pointing at a fact rather than at an opinion.
	APIReference struct {
		Status string `json:"status"`
		Reason string `json:"reason"`
	} `json:"api_reference"`
}

func main() {
	out := "web/console/src/generated/docs-facts.json"
	if len(os.Args) > 1 {
		out = os.Args[1]
	}

	f := facts{
		Schema: "heros.docs-facts/v1",
		Note: "GENERATED by cmd/docsfacts. Do not edit. `make docs-facts` regenerates; " +
			"`make docs-facts-check` fails the build on a diff.",
		ToolVersion:     cli.ToolVersion,
		ContractVersion: cli.ContractVersion,
		EnvPrefix:       cli.EnvPrefix,
		ProjectFile:     cli.ProjectFile,
		Precedence:      cli.ConfigPrecedence(),
		ExitCodes:       cli.ExitCodes(),
		Metrics:         telemetry.MetricCatalog(),
	}
	f.APIReference.Status = "absent"
	f.APIReference.Reason = "There is no OpenAPI document in this repository, and the HTTP API reference is " +
		"generated or it is not published at all. A hand-written endpoint list is a copy of the truth that " +
		"begins drifting the day it is written, and it defeats the fence — which can only check documentation " +
		"against an artifact."

	for _, c := range cli.Commands() {
		fact := commandFact{
			Name:         c.Name,
			Summary:      c.Summary,
			Availability: string(c.Avail),
			Offline:      c.Avail == cli.AvailOffline,
			NeedsAccount: c.Avail == cli.AvailNetwork,
			Example:      c.Example,
			Success:      c.Success,
			SuccessExit:  c.SuccessExit,
			Unavailable:  c.Unavailable,
			Flags:        []flagFact{},
		}
		names := append([]string(nil), c.Flags...)
		sort.Strings(names)
		for _, name := range names {
			spec, ok := cli.FlagSpec(name)
			if !ok {
				fmt.Fprintf(os.Stderr, "docsfacts: command %q lists unknown flag %q\n", c.Name, name)
				os.Exit(1)
			}
			fact.Flags = append(fact.Flags, flagFact{
				Name: spec.Name, Type: spec.Type, Default: spec.Default, Env: spec.Env, Summary: spec.Summary,
			})
		}
		f.Commands = append(f.Commands, fact)
	}

	for _, c := range distribution.Channels() {
		f.Channels = append(f.Channels, channelFact{
			ID: c.ID, Label: c.Label, GOOSes: c.GOOSes,
			Publication: string(c.Publication), Delivered: c.Delivered(), Blocker: c.Blocker,
			ManagerOwned: c.ManagerOwned, Verification: c.Verification,
			Install: c.Install, Upgrade: c.Upgrade, Uninstall: c.Uninstall, Pin: c.Pin,
		})
	}

	f.TrustClaims = distribution.ClaimIDs()

	encoded, err := json.MarshalIndent(f, "", "  ")
	if err != nil {
		fmt.Fprintln(os.Stderr, "docsfacts:", err)
		os.Exit(1)
	}
	encoded = append(encoded, '\n')
	if err := os.WriteFile(out, encoded, 0o644); err != nil {
		fmt.Fprintln(os.Stderr, "docsfacts:", err)
		os.Exit(1)
	}
	fmt.Printf("docs facts written to %s: %d command(s), %d metric(s), %d channel(s)\n",
		out, len(f.Commands), len(f.Metrics), len(f.Channels))
}
