package conversation

import (
	"sort"
	"strings"
)

// router.go routes one sentence to one intent, or abstains (design.md D5, tasks 3.1–3.3).
//
// # The metric that matters is NOT accuracy
//
// A router that is 95% accurate and never abstains silently answers a different question one time in
// twenty, and the person has no way to notice: the answer is well-formed, it is just about something
// else. A router that is 88% accurate and abstains on the remainder is strictly better here, because
// every one of its failures is VISIBLE — a refusal naming what the surface can do.
//
// So this router is permitted to abstain, and §3's evaluation reports per-intent recall and abstention
// precision as fourteen rows. 🚫 Never a mean: a single figure over fourteen intents can sit at 93%
// while `coverage` — the intent that answers "what did you NOT measure" — is routed correctly one time
// in three, and nothing in the number says so.
//
// # Why lexical and deterministic rather than a model call
//
// Three reasons, in the order they decide it:
//
//  1. **FR11 and the pin.** A repeated question must cost nothing and return the same answer. A router
//     that made a provider call would spend money before the pin was ever consulted, which puts the
//     spend on the path the determinism guarantee exists to remove.
//  2. **The abstention has to be calibrated.** A calibrated threshold needs a score that means the same
//     thing twice, and a model's self-reported confidence is not that.
//  3. **It is falsifiable.** Every routing decision here is a function of the sentence and this file.
//     A holdout run is reproducible, which is what makes "no pure-refactor exemption" (task 3.5)
//     enforceable rather than aspirational.
//
// # 🔴 What this router deliberately does not do
//
// It does not ask a clarifying question freely. PRD §14 Q3's ratified answer is *at most one
// clarification, from a closed set, never free-form* — free-form clarification is the channel through
// which an ambiguous intent becomes a confident wrong one, because the follow-up is generated by the
// same thing that was already unsure.

// Routing is one routing decision.
type Routing struct {
	// Intent is the intent chosen. Empty means ABSTAINED.
	Intent Intent
	// Confidence is the calibrated score in [0,1]. Reported even on an abstention, so the threshold's
	// effect is observable rather than inferred.
	Confidence float64
	// ClaimsRepository records whether answering requires asserting a property of the customer's
	// repository. 🔴 This is what makes FR3 structural: the emitter refuses an `answer` on a turn where
	// this is true, whatever the prose says.
	ClaimsRepository bool
	// Cause is why it abstained, in the words the refusal will carry.
	Cause string
	// SurfaceHref is where the thing asked for IS done, when the question is out of scope by name
	// (FR26). Empty for an ordinary abstention.
	SurfaceHref string
	// Runners-up, for the holdout report and for a person debugging a wrong route.
	Scores []IntentScore
}

// IntentScore is one intent's score for a question.
type IntentScore struct {
	Intent Intent
	Score  float64
}

// Abstained reports whether the router declined to route.
func (r Routing) Abstained() bool { return r.Intent == "" }

// AbstainThreshold is the calibrated confidence below which the router abstains.
//
// # How this number was chosen, and why it is written here rather than tuned in a config
//
// It is calibrated against the holdout in `router_holdout_test.go`, which contains labelled real
// questions including deliberately ambiguous and out-of-scope ones. The calibration objective is NOT
// maximum accuracy — it is: **no intent's recall may collapse, and an abstention must almost always be
// correct.** Raising it trades recall for abstention precision; lowering it does the reverse.
//
// 🔴 It is a constant rather than configuration for the reason `StepReEntryCeiling` is: a threshold an
// operator can lower is a threshold that gets lowered the first time somebody complains the agent says
// "I cannot route that" too often — and lowering it does not make the router better, it makes its
// failures invisible again.
const AbstainThreshold = 0.34

// intentTerms is the discriminating vocabulary per intent.
//
// # Why the weights are what they are
//
// A term's weight is how much it DISCRIMINATES, not how related it feels. "node" appears in nearly
// every question this surface receives, so it is worth almost nothing; "remember" belongs to exactly one
// intent, so it is worth a lot. Weighting by relatedness rather than discrimination is what produces a
// router that is confidently wrong between adjacent intents — `context` vs `memory`, `wiring` vs
// `graph` — which is the pair task 3.8 puts in the holdout precisely because the failure is invisible.
var intentTerms = map[Intent]map[string]float64{
	IntentGraph: {
		"step by step": 3, "what does": 1.5, "actually do": 2.5, "shape": 1.5,
		"diagram": 2.5, "structure": 2, "workflow": 1.5, "pipeline": 2, "nodes": 1,
	},
	IntentRunHistory: {
		"run": 2, "happened": 3, "last run": 3.5, "that run": 3.5, "trace": 2,
		"history": 2.5, "yesterday": 2, "failed run": 3, "execution": 2,
	},
	IntentCompare: {
		"better": 3, "compare": 3.5, "versus": 3, "vs": 2.5, "variant": 3,
		"than the last": 3.5, "improvement": 2, "regression": 2.5, "baseline": 2.5,
	},
	IntentPreviewChange: {
		// 🔴 "diff" is NOT here, and its absence is a decision. A diff is shown on this surface and on
		// `author` and on a proposal card — it is the most RELATED word in the product and one of the
		// least DISCRIMINATING, and weighting it here made "I want to edit this and see the diff" tie
		// with `author` and abstain. What distinguishes this intent is the HYPOTHETICAL: what *would*
		// be written, before anything is.
		"what would you write": 4, "preview": 3, "exactly would": 3.5,
		"before you change": 3.5, "transform": 3, "into my source": 3.5, "dry run": 3,
	},
	IntentDeliver: {
		"pull request": 2, "reach my repository": 4, "delivery": 3.5, "deliver": 3,
		"merge": 2, "how does": 1.5, "ship": 2.5, "land": 2,
	},
	IntentPromptModel: {
		"prompt": 3.5, "instruction": 3, "model": 3, "system message": 3.5,
		"temperature": 3, "swap the model": 4, "cheaper model": 3.5, "wording": 2.5,
	},
	IntentAuthor: {
		// 🚫 "i want to change" and "change something" were here and are gone. They are PHRASINGS, not
		// subjects: a person says "I want to change the instruction" about `prompt_model` and "I want to
		// change the order" about `graph_order`, so weighting the phrasing put `author` in a tie with
		// whatever the sentence was actually about — and a tie abstains, so the failure was a refusal
		// on a perfectly clear question. What identifies this intent is a person editing something
		// themselves: `edit`, `author`, `modify`.
		"edit": 3.5, "author": 3, "show me the diff": 3.5, "see the diff": 3.5, "modify": 2.5, "axis": 1.5,
	},
	IntentGraphOrder: {
		"order": 3, "in this order": 4, "sequence": 3, "parallel": 3.5, "wiring": 3.5,
		"before": 2, "after": 2, "run these": 2.5, "concurrently": 3.5, "topology": 3,
	},
	IntentContext: {
		"conversation history": 4, "context": 3, "what does this node get": 4,
		"context window": 3.5, "prior turns": 3.5, "passed in": 2.5, "sees": 2,
	},
	IntentMemory: {
		// ⚠️ "between calls" is 2.5, not 4, and this is the adjacent-intent calibration task 3.8 exists
		// to force. It reads like a memory phrase because the PRD's memory question contains it — but
		// "what context does this node get between calls" is an equally natural CONTEXT question, so it
		// is a temporal qualifier the two axes SHARE. Weighting a shared qualifier as a discriminator
		// made "what conversation history does this node get between calls" tie and abstain. The real
		// discriminators are what happens to the information after the call: remember, forget, persist.
		"remember": 4, "memory": 3.5, "between calls": 2.5, "recall": 3,
		"persist": 3, "forget": 3.5, "across runs": 3, "stored": 2,
	},
	// 🔴 P34 split these two, and the split is the hardest routing decision in the table because the two
	// questions SHARE THEIR NOUNS. "How many turns does it take" is the loop; "how many turns is it
	// ALLOWED to take" is the envelope, and one word apart is the whole difference.
	//
	// The weights encode that: `loop` owns the verbs of doing (reflect, retry, iterate) and `harness`
	// owns the verbs of permission (allowed, may, ceiling, limit, sandbox, spend). "turns" alone is
	// deliberately weak on both — a question containing only that word has not yet said which it means,
	// and a router confident about it would be confident about a coin flip.
	IntentLoop: {
		"how many turns": 4, "loop": 3.5, "retry": 3, "reflect": 3,
		"scaffold": 3, "iterations": 3, "iterate": 3, "turns": 2,
	},
	IntentHarness: {
		"allowed to": 4, "sandbox": 4, "spend": 3.5, "ceiling": 3.5, "envelope": 3.5,
		"harness": 3.5, "reach the network": 4, "budget": 3, "limit": 3, "guardrail": 3.5,
		"approval gate": 3.5, "how much can it spend": 4, "turns": 2,
	},
	IntentCoverage: {
		"what did you measure": 4, "what did you not": 4, "coverage": 3.5,
		"not measured": 4, "unmeasured": 3.5, "gaps": 3, "skipped": 2.5, "blind spot": 3.5,
	},
	IntentAssess: {
		"what is wrong": 3.5, "whats wrong": 3.5, "what's wrong": 3.5, "look at my repository": 4,
		"assess": 3.5, "review my": 3, "is weak": 4, "audit": 3, "health": 2.5, "problems": 2.5,
	},
	IntentImprove: {
		"fix it": 4, "fix": 2.5, "improve": 3.5, "open a pull request": 4,
		"make it better": 3.5, "optimize": 3, "optimise": 3, "and fix": 3.5,
	},
}

// proseIntents are the intents whose questions may be answered with prose because they assert nothing
// about the repository — "what does context strategy mean?" is about the PRODUCT.
//
// 🔴 This is not a property of an intent. It is a property of the QUESTION, decided in `understand`,
// and `definitionalMarkers` is how it is decided. Recorded here rather than on IntentSpec because an
// intent-level flag would make every `memory` question prose-admissible, including "does my extraction
// node remember anything?", which is a claim about a repository.
var definitionalMarkers = []string{
	"what does the term", "what do you mean by", "what is a ", "what is an ",
	"what does it mean", "definition of", "explain what", "what can you do",
	"what can i ask", "how does this product", "what is context strategy",
	"what is a harness", "what is an axis",
}

// LexicalRouter is the router.
//
// It has no fields today. It is a TYPE rather than a package-level function because §3's discipline
// requires the routing change to be run through a spike with the holdout before it lands, and a type is
// what lets a spike hold two of them side by side and compare them on the same corpus.
type LexicalRouter struct{}

// NewRouter returns the router this deployment uses.
func NewRouter() *LexicalRouter { return &LexicalRouter{} }

// Route classifies a question.
//
// The order of the decisions is the order of the answers a person needs distinguished:
//
//  1. Out of scope BY NAME (FR26) — "that is done at /app/billing", not "I cannot route that".
//  2. Below the calibrated threshold — an abstention naming what the surface can do.
//  3. Routed, with the confidence and the runners-up recorded.
func (LexicalRouter) Route(question string) Routing {
	q := normalise(question)
	if q == "" {
		return Routing{Cause: "the question is empty"}
	}

	// 1 · FR26. Account, billing and identity are SURFACES; they are not agent goals. An agent that
	// offered to change a plan or a password would have crossed from answering about a system to
	// administering an account.
	if topic, ok := outOfScopeFor(q); ok {
		return Routing{
			Cause: "changing a " + topic.Topic + " is not something this surface does; " +
				topic.Surface + " does " + topic.Does,
			SurfaceHref: topic.Surface,
		}
	}

	scores := scoreIntents(q)
	if len(scores) == 0 {
		return Routing{
			Cause:  "this question does not match anything this surface can be asked",
			Scores: nil,
		}
	}

	// 🔴 Confidence combines ABSOLUTE evidence with the MARGIN over the runner-up, and both halves are
	// load-bearing. Absolute alone routes a sentence with one weak term hit; margin alone routes a
	// sentence that matched two intents equally badly but one slightly less badly — which is exactly
	// the adjacent-intent failure (`context` vs `memory`) that a confident wrong route hides.
	top := scores[0]
	runnerUp := 0.0
	if len(scores) > 1 {
		runnerUp = scores[1].Score
	}
	absolute := top.Score / (top.Score + 4.0)
	margin := 1.0
	if top.Score > 0 {
		margin = (top.Score - runnerUp) / top.Score
	}
	confidence := absolute*0.6 + margin*0.4

	if confidence < AbstainThreshold {
		return Routing{
			Confidence: confidence,
			Cause: "this question could be about more than one of the things this surface knows, " +
				"and answering the wrong one would look exactly like answering the right one",
			Scores: scores,
		}
	}
	return Routing{
		Intent:           top.Intent,
		Confidence:       confidence,
		ClaimsRepository: !definitional(q),
		Scores:           scores,
	}
}

// scoreIntents scores every intent that matched at least one term, best first.
func scoreIntents(q string) []IntentScore {
	var out []IntentScore
	for _, spec := range intents {
		score := 0.0
		for term, weight := range intentTerms[spec.Intent] {
			if strings.Contains(q, term) {
				score += weight
			}
		}
		if score > 0 {
			out = append(out, IntentScore{Intent: spec.Intent, Score: score})
		}
	}
	sort.SliceStable(out, func(i, j int) bool {
		if out[i].Score != out[j].Score {
			return out[i].Score > out[j].Score
		}
		// Ties break by the intent set's own order, so the result is deterministic. 🔴 A tie broken by
		// map order would make the same sentence route two ways on two runs, which would make the
		// holdout's numbers meaningless without anything looking wrong.
		return out[i].Intent < out[j].Intent
	})
	return out
}

// definitional reports whether the question is about the PRODUCT rather than about the repository.
func definitional(q string) bool {
	for _, marker := range definitionalMarkers {
		if strings.Contains(q, marker) {
			return true
		}
	}
	return false
}

// outOfScopeFor finds an enumerated redirection.
//
// 🔴 It requires an ACTION word beside the topic. "my plan" appears in "what is the plan for this run",
// which is an ordinary question about a turn — and redirecting that to billing would be a confident
// wrong answer wearing a helpful hat.
func outOfScopeFor(q string) (OutOfScopeTopic, bool) {
	actions := []string{"change", "update", "upgrade", "downgrade", "cancel", "reset", "add", "remove",
		"invite", "revoke", "delete", "set my", "switch my"}
	hasAction := false
	for _, a := range actions {
		if strings.Contains(q, a) {
			hasAction = true
			break
		}
	}
	if !hasAction {
		return OutOfScopeTopic{}, false
	}
	for _, t := range outOfScope {
		if strings.Contains(q, t.Topic) {
			return t, true
		}
	}
	return OutOfScopeTopic{}, false
}

// normalise lowercases and collapses whitespace and punctuation to spaces, so a term table written in
// plain words matches a sentence written with punctuation. Deliberately simple: a stemmer would make
// the router's behaviour depend on a library's version, and the holdout would stop being reproducible.
func normalise(s string) string {
	var b strings.Builder
	b.Grow(len(s) + 2)
	b.WriteByte(' ')
	lastSpace := true
	for _, r := range strings.ToLower(s) {
		switch {
		case r >= 'a' && r <= 'z', r >= '0' && r <= '9', r == '\'':
			b.WriteRune(r)
			lastSpace = false
		default:
			if !lastSpace {
				b.WriteByte(' ')
				lastSpace = true
			}
		}
	}
	out := b.String()
	if !strings.HasSuffix(out, " ") {
		out += " "
	}
	return out
}
