-- 0003_contributory_edges — dependencies whose results are used if available.
--
-- # Why a new file rather than editing 0001
--
-- Every database that already exists has run 0001, and its `CREATE TABLE IF NOT EXISTS` is a no-op the
-- second time — so a column added there would never appear on any database that already ran it. The
-- migration model here is "run them all, let idempotence absorb the repeats", and that only works if a
-- change is expressed as a new statement rather than an edit to an old one.
--
-- # What the column carries
--
-- A required dependency must SUCCEED before its dependent runs. A contributory one must merely be
-- TERMINAL. The distinction exists because an eval set is generated by four independent strategies and
-- one of them fails whenever no trace source is connected: with every generator required, that failure
-- blocked the quality gate and a run holding three generators' worth of good cases delivered nothing.

ALTER TABLE tasks ADD COLUMN IF NOT EXISTS contributes JSONB NOT NULL DEFAULT '[]'::jsonb;

-- The same array-shape invariant as depends_on: a nil Go slice marshals to the scalar `null`, and
-- jsonb_array_elements_text on a scalar raises at CLAIM time, far from the write that caused it.
ALTER TABLE tasks DROP CONSTRAINT IF EXISTS tasks_contributes_is_array;
ALTER TABLE tasks ADD CONSTRAINT tasks_contributes_is_array CHECK (jsonb_typeof(contributes) = 'array');
