#!/bin/sh
# install.sh installs the `heros` CLI on macOS and Linux: detect → download → VERIFY → place on PATH.
#
#   curl -fsSL https://raw.githubusercontent.com/damonleelcx/heros-agent/v0.21.0/scripts/install.sh | sh
#
# Environment:
#   HEROS_VERSION=0.20.0     install a specific version instead of the latest (this is the rollback, task 3.8)
#   HEROS_INSTALL_DIR=/path   where to place the binary (default: the first writable of /usr/local/bin, ~/.local/bin)
#   HEROS_UNINSTALL=1         remove an installed heros and exit
#
# ─────────────────────────────────────────────────────────────────────────────────────────────────────────
# # Why this script verifies for you, and why it stops instead of continuing
#
# The `heros` binary runs inside CI with repository access. A compromised release is a compromise of every
# customer's build, so the signature is not a nicety a careful user checks — it is a step that has to happen
# on every install, including the ones where nobody is watching. The single most likely real-world failure is
# a user (or a naïve wrapper script) that installs the binary and never runs the verify step. So the installer
# runs it, and on any failure it STOPS: there is no "install anyway, unverified" path. An installer with a
# fallback like that has traded 安全 for the convenience of not handling the error, which is exactly the trade
# the project's own rules forbid.
#
# Nothing is placed on PATH until every check has passed. The download lives in a temporary directory that is
# removed on exit, success or failure, so a refused install leaves no half-installed binary behind for
# someone to find later and run.
#
# # Why it does NOT verify with the binary it just downloaded
#
# That is circular, and the circularity is not theoretical: an attacker who can serve you a `heros` binary can
# serve you one whose `verify` subcommand prints "OK: signature verifies". The verifier has to be a program
# that was already on the machine before this download. So the script uses, in order of preference:
#
#   1. ssh-keygen -Y verify   — present on stock macOS and wherever openssh-client is installed
#   2. openssl pkeyutl -rawin — OpenSSL 3.x, verifies the raw signature (the same bytes `heros upgrade` checks)
#   3. an already-installed, previously-verified `heros verify-release`  — the upgrade path
#
# and if none of them is available it REFUSES, naming the three ways forward. Note what is not on that list:
# stock macOS `/usr/bin/openssl` is LibreSSL, which cannot verify ed25519 at all. An installer that only knew
# how to use OpenSSL would silently have no verifier on the primary developer platform — which is why the
# release publishes the same signature in sshsig form (see internal/release/sshsig.go).
#
# # The pinned trust root
#
# The public key below is PINNED IN THIS SCRIPT. It is never downloaded: whoever can serve you a binary can
# serve you a key, so a fetched key proves nothing. Held identical to internal/release/trustroot.go by
# TestInstallScriptPinsTheTrustRoot — if they ever drift, the installer verifies against a key the binary
# rejects, and each side looks fine on its own.
# ─────────────────────────────────────────────────────────────────────────────────────────────────────────
set -eu

REPO="damonleelcx/heros-agent"
# The download and API endpoints are overridable ONLY so this script can be exercised against a local
# release fixture — a fresh-machine smoke test and a tamper red-check cannot be written against a script
# whose URLs are hard-coded, and a verification step that has never been shown to reject is treated as
# absent (QA rule).
#
# 🔴 This is not a hole. The trust root below is PINNED: pointing the installer at another host changes where
# the bytes come from, not which key must have signed them. A redirected download still cannot install
# anything the heros release key did not sign, which is the property that matters.
RELEASES="${HEROS_RELEASE_BASE_URL:-https://github.com/${REPO}/releases}"
API="${HEROS_RELEASE_API_URL:-https://api.github.com/repos/${REPO}/releases}"

# ── the pinned trust root (generated by `herossign signers`) ────────────────────────────────────────────
HEROS_PUBKEY_SSH='ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIMniGcZXM+AMZ6J5ldw3N7P3PZp6fJHsKvbgRGNzK1YK'
HEROS_PUBKEY_HEX='c9e219c65733e00c67a27995dc3737b3f73d9a7a7c91ec2af6e04463732b560a'
HEROS_SIGNER_ID='heros-release'
HEROS_SIG_NAMESPACE='file'

say()  { printf 'heros install: %s\n' "$*"; }
warn() { printf 'heros install: %s\n' "$*" >&2; }

# die is the only exit path for a failure. It says what went wrong AND what to do next, because a user who
# hits a refused install has one question and it is not "what happened".
die() {
  printf '\n' >&2
  printf 'heros install: ⛔ %s\n' "$1" >&2
  if [ $# -gt 1 ]; then
    shift
    printf '\n' >&2
    for line in "$@"; do printf '  %s\n' "${line}" >&2; done
  fi
  printf '\nNothing was installed. No partial install was left behind.\n' >&2
  exit 1
}

TMP=""
# The status is captured and re-exited DELIBERATELY. Without it, the trap's own last command decides the
# script's exit status: when TMP is empty the `[ -n ]` test fails, and a successful uninstall exited 1 — which
# a CI step would have reported as a failed install. And returning a bare 0 instead would be worse: it would
# mask every real failure, turning a refused install into a green step.
cleanup() {
  status=$?
  if [ -n "${TMP}" ]; then rm -rf "${TMP}"; fi
  exit "${status}"
}
trap cleanup EXIT HUP INT TERM

# ── uninstall (task 3.8) ────────────────────────────────────────────────────────────────────────────────
if [ "${HEROS_UNINSTALL:-}" = "1" ]; then
  found=0
  for dir in "${HEROS_INSTALL_DIR:-}" /usr/local/bin "${HOME}/.local/bin" "${HOME}/bin"; do
    [ -n "${dir}" ] || continue
    if [ -f "${dir}/heros" ]; then
      rm -f "${dir}/heros" && say "removed ${dir}/heros" && found=1
    fi
  done
  if [ "${found}" = "0" ]; then
    say "no heros binary found in the directories this installer writes to."
    say "if you installed with a package manager, uninstall with its own command:"
    say "  brew uninstall heros · scoop uninstall heros · winget uninstall heros"
    say "  sudo apt-get remove heros · sudo dnf remove heros"
  fi
  exit 0
fi

# ── 1. detect the target ────────────────────────────────────────────────────────────────────────────────
detect_target() {
  os="$(uname -s)"
  arch="$(uname -m)"
  case "${os}" in
    Darwin) goos=darwin ;;
    Linux)  goos=linux ;;
    *) die "unsupported operating system: ${os}" \
           "heros publishes native binaries for macOS and Linux, and a Windows build installed with" \
           "scripts/install.ps1. The supported-target matrix is in the README." ;;
  esac
  case "${arch}" in
    x86_64|amd64)  goarch=amd64 ;;
    arm64|aarch64) goarch=arm64 ;;
    *) die "unsupported architecture: ${arch}" \
           "heros publishes amd64 and arm64 builds. Adding an architecture is a new native runner in the" \
           "release matrix, not a redesign — open an issue and say which one." ;;
  esac

  # The musl check is not pedantry: the CLI links CGO tree-sitter frontends against glibc, so a glibc binary
  # does not run on musl. Without this the install "succeeds" and the first `heros discover` dies with a
  # loader error the user has no way to interpret.
  if [ "${goos}" = "linux" ] && [ ! -e /lib/ld-linux-x86-64.so.2 ] && [ ! -e /lib/ld-linux-aarch64.so.1 ] \
     && [ ! -e /lib64/ld-linux-x86-64.so.2 ]; then
    if [ -e /lib/ld-musl-x86_64.so.1 ] || [ -e /lib/ld-musl-aarch64.so.1 ] || [ -f /etc/alpine-release ]; then
      die "this is a musl system (Alpine or similar), and heros has no native musl build" \
          "The CLI links tree-sitter language frontends against glibc; a glibc binary does not run on musl," \
          "and shipping a half-tested static build would fail inside your CI instead of here." \
          "" \
          "Use the container image, which carries the same CLI in a glibc base:" \
          "  docker run --rm -v \"\$PWD:/repo\" ghcr.io/damonleelcx/heros:latest discover --repo /repo"
    fi
  fi
}

# ── 2. resolve the version ──────────────────────────────────────────────────────────────────────────────
have() { command -v "$1" >/dev/null 2>&1; }

# The default endpoints are HTTPS-only, enforced at the curl layer rather than trusted to the URL string.
# An explicitly overridden endpoint may be plain HTTP — that is the local-fixture case — and the override says
# so out loud. What does NOT change is the signature requirement: the transport is not what protects you here,
# the pinned key is, and that is why a downgraded transport is a warning rather than a refusal.
case "${RELEASES}" in
  https://*) CURL_PROTO_ARGS="--proto =https --tlsv1.2" ;;
  *) CURL_PROTO_ARGS=""
     warn "endpoint ${RELEASES} is not HTTPS (explicitly overridden). The signature check is unchanged." ;;
esac

fetch() { # fetch <url> <dest>
  if have curl; then
    # shellcheck disable=SC2086 # CURL_PROTO_ARGS must word-split into separate flags
    curl -fsSL ${CURL_PROTO_ARGS} -o "$2" "$1" || return 1
  elif have wget; then
    wget -qO "$2" "$1" || return 1
  else
    die "neither curl nor wget is available" \
        "Install one of them, or download the release by hand from ${RELEASES} and follow" \
        "docs/release/install.md's manual verification."
  fi
}

resolve_version() {
  if [ -n "${HEROS_VERSION:-}" ]; then
    version="${HEROS_VERSION#v}"
    say "installing pinned version ${version}"
    return
  fi
  # The tag is read from the Releases API rather than from a "latest" text file, so there is no second place
  # that has to be updated when a release ships.
  fetch "${API}/latest" "${TMP}/latest.json" \
    || die "cannot reach the GitHub Releases API to find the latest version" \
           "Check your network, or pin a version: HEROS_VERSION=0.20.0 sh install.sh" \
           "Releases are listed at ${RELEASES}"
  version="$(sed -n 's/.*"tag_name"[[:space:]]*:[[:space:]]*"v\{0,1\}\([^"]*\)".*/\1/p' "${TMP}/latest.json" | head -n1)"
  [ -n "${version}" ] || die "could not read a version from the Releases API response" \
      "Pin one instead: HEROS_VERSION=0.20.0 sh install.sh"
  say "latest version is ${version}"
}

# ── 3. checksum verification (always available) ─────────────────────────────────────────────────────────
sha256_of() { # sha256_of <file> → lowercase hex on stdout
  if have sha256sum; then
    sha256sum "$1" | awk '{print $1}'
  elif have shasum; then
    shasum -a 256 "$1" | awk '{print $1}'
  else
    die "no sha256 tool found (looked for sha256sum and shasum)" \
        "Both are part of a base install on macOS and every mainstream Linux. Without one, the download" \
        "cannot be checked at all, and installing an unchecked binary is not something this script does."
  fi
}

verify_checksum() { # verify_checksum <file> <manifest>
  want="$(awk -v f="$(basename "$1")" '$2 == f {print $1}' "$2" | head -n1)"
  [ -n "${want}" ] || die "the release manifest does not list $(basename "$1")" \
      "This means the release is incomplete for your platform — not that your download failed." \
      "Report it with the version (${version}) and platform (${goos}/${goarch})."
  got="$(sha256_of "$1")"
  if [ "${want}" != "${got}" ]; then
    die "CHECKSUM MISMATCH for $(basename "$1")" \
        "manifest: ${want}" \
        "download: ${got}" \
        "" \
        "The bytes you received are not the bytes the release published. Do not run this file." \
        "Retry once in case of a truncated download; if it repeats, report it."
  fi
  say "✓ checksum matches the release manifest"
}

# ── 4. signature verification, with a verifier that predates this download ──────────────────────────────
verify_signature() { # verify_signature <manifest> <sshsig> <rawsig>
  manifest="$1"; sshsig="$2"; rawsig="$3"

  # (1) ssh-keygen — the one that is actually present on a stock machine.
  if have ssh-keygen && ssh-keygen -Y verify 2>&1 | grep -q namespace; then
    signers="${TMP}/allowed_signers"
    printf '%s namespaces="%s" %s\n' "${HEROS_SIGNER_ID}" "${HEROS_SIG_NAMESPACE}" "${HEROS_PUBKEY_SSH}" > "${signers}"
    if ssh-keygen -Y verify -f "${signers}" -I "${HEROS_SIGNER_ID}" \
         -n "${HEROS_SIG_NAMESPACE}" -s "${sshsig}" < "${manifest}" >/dev/null 2>&1; then
      say "✓ signature verified against the pinned heros release key (ssh-keygen)"
      return 0
    fi
    die "SIGNATURE VERIFICATION FAILED" \
        "The checksum manifest is not signed by the heros release key pinned in this installer." \
        "Either the release was tampered with in transit, or the release key was rotated and this" \
        "installer is older than the rotation." \
        "" \
        "Do not install this binary. Get the current installer from:" \
        "  ${RELEASES}/latest"
  fi

  # (2) OpenSSL 3.x can verify the raw signature — the same bytes `heros upgrade` checks. Probed by
  # capability, not by version string: LibreSSL reports a version too, and cannot do this.
  if have openssl && openssl pkeyutl -help 2>&1 | grep -q -- -rawin; then
    key="${TMP}/heros.pub.der"
    # A raw ed25519 public key becomes a DER SubjectPublicKeyInfo by prefixing a fixed 12-byte header.
    { printf '302a300506032b6570032100'; printf '%s' "${HEROS_PUBKEY_HEX}"; } \
      | ( have xxd && xxd -r -p || od -An -tx1 -v | tr -d ' \n' | xxd -r -p ) > "${key}" 2>/dev/null \
      || { warn "could not assemble the DER public key; trying the next verifier"; key=""; }
    if [ -n "${key}" ] && [ -s "${key}" ]; then
      sigbin="${TMP}/sig.bin"
      tr -d '\n' < "${rawsig}" | ( have xxd && xxd -r -p ) > "${sigbin}" 2>/dev/null || true
      if [ -s "${sigbin}" ] && openssl pkeyutl -verify -pubin -inkey "${key}" -keyform DER \
           -rawin -in "${manifest}" -sigfile "${sigbin}" >/dev/null 2>&1; then
        say "✓ signature verified against the pinned heros release key (openssl)"
        return 0
      fi
      die "SIGNATURE VERIFICATION FAILED" \
          "openssl refused the release signature over the checksum manifest." \
          "Do not install this binary. Get the current installer from ${RELEASES}/latest"
    fi
  fi

  # (3) An already-installed heros. Independent of this download, so not circular — and it is the common
  # case for an upgrade.
  if have heros && heros verify-release --help >/dev/null 2>&1; then
    if heros verify-release --manifest "${manifest}" --sig "${rawsig}" >/dev/null 2>&1; then
      say "✓ signature verified by the heros already installed on this machine"
      return 0
    fi
    die "SIGNATURE VERIFICATION FAILED" \
        "The heros already installed on this machine refuses the new release's signature." \
        "Do not replace it. Get the current installer from ${RELEASES}/latest"
  fi

  # (4) No verifier that predates the download. Refuse — and name every way forward.
  die "no ed25519 verifier is available on this machine, so the release signature cannot be checked" \
      "This installer will not place an unverified binary on your PATH, and it will not use the binary it" \
      "just downloaded to verify itself — an attacker who can serve you a binary can serve you one that" \
      "prints 'signature OK'." \
      "" \
      "Any one of these fixes it:" \
      "  1. install with a package manager, which verifies the checksum from the signed manifest for you:" \
      "       brew install heros-foreal/tap/heros" \
      "  2. install an ed25519-capable verifier and re-run:" \
      "       macOS: brew install openssh    ·    Debian/Ubuntu: apt-get install -y openssh-client" \
      "  3. use the container image, which needs no local install:" \
      "       docker run --rm -v \"\$PWD:/repo\" ghcr.io/damonleelcx/heros:latest discover --repo /repo"
}

# ── the mark ────────────────────────────────────────────────────────────────────────────────────────────
# print_mark draws the Heros mark — the H that is also a confidence interval: two end caps, the span, and a
# point estimate on it. The rows are held identical to scripts/install.ps1 and to the source SVG's figure by
# TestInstallScriptsCarryTheSameMark; edit internal/distribution/mark.go, not this copy.
#
# It prints on a SUCCESSFUL install only. A banner at the top of a run that then refuses would put the brand
# on a failure and, worse, would be the last thing a user saw before "Nothing was installed" — this script
# spends 300 lines refusing carefully, and a celebratory logo above a refusal undoes that.
#
# Three things can make it wrong, so all three are checked rather than assumed:
#
#   1. stdout is not a terminal. `curl … | sh` pipes stdin, NOT stdout, so a real install still passes this;
#      what fails it is `… | sh > install.log` and CI, where the escapes would be recorded as garbage.
#   2. colour is unwanted (NO_COLOR, TERM=dumb) or unavailable at the depth we want. The ladder degrades
#      truecolor → 256 → the terminal's own cyan → no colour at all, rather than assuming 24-bit.
#   3. the locale cannot carry box-drawing characters, in which case the ASCII drawing of the same figure is
#      printed. Mojibake at the end of an install reads as a broken install.
print_mark() {
  [ -t 1 ] || return 0

  mark_on=""
  mark_off=""
  if [ -z "${NO_COLOR:-}" ] && [ "${TERM:-}" != "dumb" ]; then
    case "${COLORTERM:-}" in
      truecolor|24bit) mark_on="$(printf '\033[38;2;46;207;168m')" ;;
      *)
        case "${TERM:-}" in
          *256color*|*direct*) mark_on="$(printf '\033[38;5;43m')" ;;
          *) mark_on="$(printf '\033[36m')" ;;
        esac
        ;;
    esac
    mark_off="$(printf '\033[0m')"
  fi

  # The charset is read from the locale rather than probed by printing: a terminal that cannot render the
  # glyph will happily accept the bytes and show boxes, so there is nothing to detect after the fact.
  case "${LC_ALL:-${LC_CTYPE:-${LANG:-}}}" in
    *UTF-8*|*utf-8*|*UTF8*|*utf8*)
      printf '  %s┃         ┃%s\n' "${mark_on}" "${mark_off}"
      printf '  %s┃         ┃%s\n' "${mark_on}" "${mark_off}"
      printf '  %s┃━━━ ● ━━━┃%s\n' "${mark_on}" "${mark_off}"
      printf '  %s┃         ┃%s\n' "${mark_on}" "${mark_off}"
      printf '  %s┃         ┃%s\n' "${mark_on}" "${mark_off}"
      ;;
    *)
      printf '  %s|         |%s\n' "${mark_on}" "${mark_off}"
      printf '  %s|         |%s\n' "${mark_on}" "${mark_off}"
      printf '  %s|--- o ---|%s\n' "${mark_on}" "${mark_off}"
      printf '  %s|         |%s\n' "${mark_on}" "${mark_off}"
      printf '  %s|         |%s\n' "${mark_on}" "${mark_off}"
      ;;
  esac
  printf '\n'
}

# ── 5. choose an install directory ──────────────────────────────────────────────────────────────────────
choose_dir() {
  if [ -n "${HEROS_INSTALL_DIR:-}" ]; then
    dest="${HEROS_INSTALL_DIR}"
    mkdir -p "${dest}" 2>/dev/null || die "cannot create ${dest}" "Pick a writable HEROS_INSTALL_DIR."
    [ -w "${dest}" ] || die "${dest} is not writable" "Pick a writable HEROS_INSTALL_DIR, or run with sudo."
    return
  fi
  for cand in /usr/local/bin "${HOME}/.local/bin" "${HOME}/bin"; do
    if [ -d "${cand}" ] && [ -w "${cand}" ]; then dest="${cand}"; return; fi
  done
  # ~/.local/bin is the fallback rather than sudo: an installer that escalates privileges on its own is a
  # worse default than one that installs to the user's own directory and says so.
  dest="${HOME}/.local/bin"
  mkdir -p "${dest}" || die "cannot create ${dest}"
  say "installing to ${dest} (no writable system directory found)"
}

# ── run ─────────────────────────────────────────────────────────────────────────────────────────────────
TMP="$(mktemp -d)"
detect_target
say "target ${goos}/${goarch}"
resolve_version

ext=""; [ "${goos}" = "windows" ] && ext=".exe"
asset="heros-${version}-${goos}-${goarch}${ext}"
base="${RELEASES}/download/v${version}"

say "downloading ${asset}"
fetch "${base}/${asset}" "${TMP}/${asset}" \
  || die "cannot download ${asset}" \
         "Either the version does not exist or your platform has no asset in it." \
         "Available releases: ${RELEASES}"
fetch "${base}/SHA256SUMS" "${TMP}/SHA256SUMS" \
  || die "cannot download the checksum manifest for v${version}" \
         "A release with no manifest cannot be verified, and this installer does not install unverified bytes."
fetch "${base}/SHA256SUMS.sshsig" "${TMP}/SHA256SUMS.sshsig" || true
fetch "${base}/SHA256SUMS.sig" "${TMP}/SHA256SUMS.sig" || true
if [ ! -s "${TMP}/SHA256SUMS.sshsig" ] && [ ! -s "${TMP}/SHA256SUMS.sig" ]; then
  die "release v${version} carries no signature over its checksum manifest" \
      "Checksums prove the download is intact; only the signature proves who produced it." \
      "This installer refuses an unsigned release. Report it with the version."
fi

# Order matters and is not arbitrary: the checksum proves the binary matches the manifest, and the signature
# proves the manifest is ours. Verifying the signature first and the checksum second would leave a window in
# which a valid manifest is trusted about a file nobody checked.
verify_checksum "${TMP}/${asset}" "${TMP}/SHA256SUMS"
verify_signature "${TMP}/SHA256SUMS" "${TMP}/SHA256SUMS.sshsig" "${TMP}/SHA256SUMS.sig"

choose_dir
chmod +x "${TMP}/${asset}"
# Written to a temporary name in the destination and then renamed, so a running `heros` is never a
# half-overwritten file: rename within a filesystem is atomic.
mv "${TMP}/${asset}" "${dest}/.heros.new"
mv "${dest}/.heros.new" "${dest}/heros"
printf '\n'
print_mark
say "✓ installed ${dest}/heros"

# ── first-run OS trust notice, printed only while the release still needs it ─────────────────────────────
if [ "${goos}" = "darwin" ]; then
  if have xattr && xattr "${dest}/heros" 2>/dev/null | grep -q com.apple.quarantine; then
    printf '\n'
    say "macOS quarantined this download because it is not notarized. Clear it with exactly:"
    printf '    xattr -d com.apple.quarantine %s/heros\n' "${dest}"
    say "or install with Homebrew (brew install heros-foreal/tap/heros), which is not quarantined."
  fi
fi

case ":${PATH}:" in
  *":${dest}:"*) ;;
  *) printf '\n'; say "${dest} is not on your PATH. Add it:"
     printf '    export PATH="%s:$PATH"\n' "${dest}" ;;
esac

printf '\n'
say "next: cd into a repository and run"
printf '    heros doctor      # check this machine is ready\n'
printf '    heros discover    # find the agent workflow in your code\n'
