// Command erroreportdoc renders the P24 event allowlists into a review document.
//
// # Why the document is GENERATED and not written
//
// `internal/erroreport/allowlist.go` says the published contract document "renders from this list", and
// a sentence like that is true until the afternoon somebody adds a field. The failure is quiet and
// expensive in a specific way: a security reviewer reads the document, answers "what can an error event
// contain" from it, and is wrong — while every test stays green, because nothing was checking the prose.
//
// So the document is produced by this program from the table in the code, and `-check` regenerates it
// into memory and diffs. A field added to the allowlist without regenerating is a RED BUILD, which is
// the only form of "the doc cannot drift" that survives contact with a deadline.
//
// The same shape as `cmd/consoletypes`: one pass, one artifact, a `-check` gate.
//
//	go run ./cmd/erroreportdoc            # write the document
//	go run ./cmd/erroreportdoc -check     # regenerate into memory and diff — the CI gate
package main

import (
	"bytes"
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/heros-foreal/agentd/internal/errorcode"
	"github.com/heros-foreal/agentd/internal/erroreport"
)

// Target is the document this program owns, relative to the repository root.
const Target = "docs/decisions/error-event-allowlist.md"

func main() {
	check := flag.Bool("check", false, "regenerate into memory and diff against the checked-in document")
	root := flag.String("root", ".", "repository root")
	flag.Parse()

	rendered := render()
	path := filepath.Join(*root, Target)

	if *check {
		existing, err := os.ReadFile(path)
		if err != nil {
			fmt.Fprintf(os.Stderr, "erroreportdoc: cannot read %s: %v\n", Target, err)
			fmt.Fprintf(os.Stderr, "  run: go run ./cmd/erroreportdoc\n")
			os.Exit(1)
		}
		if !bytes.Equal(existing, rendered) {
			fmt.Fprintf(os.Stderr,
				"erroreportdoc: %s has DRIFTED from internal/erroreport's allowlist.\n"+
					"  The document is the answer a security reviewer gets to \"what can an error event\n"+
					"  contain\". A stale one is a wrong answer that nothing else in the build notices.\n"+
					"  run: go run ./cmd/erroreportdoc\n", Target)
			os.Exit(1)
		}
		fmt.Printf("erroreportdoc: %s matches the allowlist (%d field(s), %d error code(s))\n",
			Target, len(erroreport.Allowlist), len(errorcode.All))
		return
	}

	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		fmt.Fprintf(os.Stderr, "erroreportdoc: %v\n", err)
		os.Exit(1)
	}
	if err := os.WriteFile(path, rendered, 0o644); err != nil {
		fmt.Fprintf(os.Stderr, "erroreportdoc: %v\n", err)
		os.Exit(1)
	}
	fmt.Printf("erroreportdoc: wrote %s\n", Target)
}

func render() []byte {
	var b strings.Builder

	b.WriteString("<!-- GENERATED by `go run ./cmd/erroreportdoc` from internal/erroreport and\n")
	b.WriteString("     internal/errorcode. Do not edit: `go run ./cmd/erroreportdoc -check` fails the\n")
	b.WriteString("     build on any difference, and an edit here would be silently reverted. Change the\n")
	b.WriteString("     table in the code. -->\n\n")

	b.WriteString("# P24 — what an error event may contain\n\n")
	b.WriteString("This is the complete answer. There is no second list, no configuration that widens it, and no\n")
	b.WriteString("field that is filtered rather than absent: the transmitted event is BUILT from the table below,\n")
	b.WriteString("field by field, and anything not named here does not exist on the wire.\n\n")

	b.WriteString("The asymmetry that makes construction worth its cost:\n\n")
	b.WriteString("| | a new field on an internal error is… | discovered… |\n|---|---|---|\n")
	b.WriteString("| Denylist (serialize, then strip) | **sent**, silently | externally, by a customer |\n")
	b.WriteString("| Allowlist (construct) | **absent**, visibly | here, as a missing feature |\n\n")

	b.WriteString("---\n\n## The error-event allowlist\n\n")
	b.WriteString("| Field | Category | Why it is structure, not content |\n|---|---|---|\n")
	for _, f := range erroreport.Allowlist {
		fmt.Fprintf(&b, "| `%s` | %s | %s |\n", f.Name, f.Category, f.Why)
	}
	fmt.Fprintf(&b, "\n%d field(s), in the order the code declares them.\n\n", len(erroreport.Allowlist))

	b.WriteString("### By category\n\n")
	byCategory := map[string][]string{}
	for _, f := range erroreport.Allowlist {
		byCategory[f.Category] = append(byCategory[f.Category], f.Name)
	}
	categories := make([]string, 0, len(byCategory))
	for c := range byCategory {
		categories = append(categories, c)
	}
	sort.Strings(categories)
	for _, c := range categories {
		fmt.Fprintf(&b, "- **%s** — `%s`\n", c, strings.Join(byCategory[c], "`, `"))
	}

	b.WriteString("\n---\n\n## Never permitted, and not expressible as a field\n\n")
	b.WriteString("Each of these is absent because there is no field for it, not because a filter removes it.\n\n")
	for _, item := range neverPermitted {
		fmt.Fprintf(&b, "- %s\n", item)
	}

	b.WriteString("\n---\n\n## `error.code` — the only message-shaped field\n\n")
	b.WriteString("An error's message body is dropped. What survives is a classification drawn from the central\n")
	b.WriteString("enum, and a value that is not a member of it is replaced by `UNKNOWN` rather than passed\n")
	b.WriteString("through — so a literal typed at a call site is absent from the wire instead of quietly present\n")
	b.WriteString("on it. The complete set:\n\n")
	for _, c := range errorcode.All {
		fmt.Fprintf(&b, "- `%s`\n", c)
	}
	fmt.Fprintf(&b, "\n%d code(s).\n", len(errorcode.All))

	b.WriteString("\n---\n\n## The stated numbers\n\n")
	b.WriteString("| Setting | Value | Basis |\n|---|---|---|\n")
	fmt.Fprintf(&b, "| Sample rate | `%v` | A defect **inbox**, not a rate source. Every frequency question is answered from the telemetry substrate, where events are complete. The first occurrence of a new defect is the one that matters, and a sampled inbox drops it with the same probability as the thousandth. |\n", erroreport.SampleRate)
	fmt.Fprintf(&b, "| Per-issue rate limit | `%d` per `%s` | Beyond the first few, each copy of the same failure tells an operator nothing and costs budget a rarer defect needs. |\n", erroreport.PerIssueRateLimit, erroreport.RateInterval)
	fmt.Fprintf(&b, "| Transmit budget | `%d` per `%s` | A bound that holds even when the per-issue limiter is defeated by a failure that varies its type or frame each time. |\n", erroreport.TransmitBudget, erroreport.RateInterval)
	fmt.Fprintf(&b, "| Queue depth | `%d`, overflow **drops** | Blocking would put an incident inbox in the request path; growing would turn a transmit outage into a memory leak. |\n", erroreport.QueueDepth)
	fmt.Fprintf(&b, "| Performance tracing | `%v` | Latency is already measured by the substrate, per call, joined to runs, unsampled. |\n", erroreport.TracingEnabled)
	fmt.Fprintf(&b, "| Profiling | `%v` | A profile carries function-level timing of code paths operating on customer content — structure this boundary has no way to bound. |\n", erroreport.ProfilingEnabled)

	b.WriteString("\n---\n\n## Deployment posture\n\n")
	fmt.Fprintf(&b, "Configured by exactly one variable, `%s`. There is no fallback, no file and no discovered\n", erroreport.EnvDSN)
	b.WriteString("default. Empty means **absent**: no transmit, no warning, readiness reports `absent`. That is the\n")
	b.WriteString("expected state on a customer's Compose or Kubernetes install and on an air-gapped network.\n\n")
	fmt.Fprintf(&b, "`%s` is a label from a closed set — `%s` — and an unrecognised value is reported as\n",
		erroreport.EnvEdition, strings.Join(erroreport.Editions, "`, `"))
	b.WriteString("`unknown` with a WARN rather than transmitted.\n")

	return []byte(b.String())
}

// neverPermitted is the design's list, rendered so the document states both halves. It lives here
// rather than in the package because it is a list of things that are NOT fields — there is nothing in
// the code to enumerate, which is the point.
var neverPermitted = []string{
	"Error message bodies, other than a value from the central `error.code` enum",
	"Request bodies",
	"Request and response headers",
	"Query strings",
	"Breadcrumb, fetch, XHR and navigation URLs — there is no breadcrumb collection at all",
	"Console output",
	"DOM breadcrumbs and click-target text",
	"Local variables",
	"Source context lines for any frame that is not platform code",
	"Environment-variable values",
	"Provider credentials",
	"Prompt, completion, source and diff text",
	"Hostnames and server names",
	"IP addresses",
	"Email addresses",
	"Tenant names",
}
